### ISSUE TITLE
Make PolymorpicSerializer serializer to work in JS 

### ISSUE THREAD

**Issue by neworld** [Kotlin/kotlinx.serialization#101]
Currently `PolymorpicSerializer` works only in JVM.

**Comment by Whathecode** [comment]
Is there an estimate when this would become available? I am currently looking into alternatives to deserialize JSON output from kotlinx.serialization in Typescript/JS. If this were planned to be released soon I might postpone this instead.

**Comment by recomap** [comment]
@sandwwraith Can you guys let us know whether anybody is working on it and/or give us a very very rough ETA? I believe a lot of people depend on that feature and I'm thinking about writing my own hacky, simplified serialization lib if polymorphic serializers wont' work in kotlinx serialization soon. But I need to know whether it makes sense to wait or invest time on writing something on my own... Thanks!

**Comment by Whathecode** [comment]
In multiplatform projects, JavaScript compilation fails when applying `@Serializable` attributes to polymorph class hierarchies.

Assuming polymorph JavaScript serialization will be supported in the future, I still want to be able to apply `@Serializable` to classes in a 'common' module. For now I am fine with serialization solely working when targeting the JVM.

To not break compilation, I do the following. In common:
`expect annotation class Serializable()`

In JS:
```
annotation class NotSerializable
actual typealias Serializable = NotSerializable
```

In JVM: `actual typealias Serializable = kotlinx.serialization.Serializable`

Perhaps this is of use to others.

**Comment by pdvrieze** [comment]
Javascript has a number of limitations:
* It does not support annotations - this could be emulated but a standard way would be very beneficial, it has to happen at kotlin compiler level
* There is almost no reflection support - PolymorphicSerializer in Java uses `Class.forName` to get the class. This API is not available in Javascript. In general javascript reflection is very limited for Kotlin. It may be possible to write related code to load a prototype in Javascript, but the problem remains that annotations are not supported so the deserializer cannot determine the correct deserializer to use for the dynamically determined child.
* An alternative would be to enumerate all possible subtypes at compiletime and then not need to use reflection.

**Comment by Whathecode** [comment]
I got polymorph serialization up and running in JavaScript for my particular use case. It relies on specifying custom serializers on class members which need to be serialized as polymorph. Serializing objects as polymorph is thus explicit rather than implicit. Compilation warnings occur if no explicit serializer is specified. This seems very much in line [with the design proposal for Kotlin 1.3](https://github.com/Kotlin/KEEP/blob/serialization/proposals/extensions/serialization.md#polymorphism).

> Polymorphic serialization is never enabled automatically. To enable this feature, use `@SerializableWith(PolymorphicSerializer::class)` or just `@Polymorphic` on the property.

To make this work with JavaScript I simply adopted the existing `PolymorphicSerializer` and added static functions through which polymorph types and their serializers can be registered. The [full class can be found here (although I will move it to a common library soon)](https://github.com/cph-cachet/carp.core-kotlin/blob/js-serialization/carp.protocols.core/carp.protocols.core-common/src/main/dk/cachet/carp/protocols/domain/serialization/PolymorphicSerializer.kt).

```
object PolymorphicSerializer : KSerializer<Any>
{
    override val serialClassDesc: KSerialClassDesc = PolymorphicSerializerClassDesc

    private val simpleNameSerializers = mutableMapOf<String, KSerializer<Any>>()
    private val qualifiedSerializers = mutableMapOf<String, KSerializer<Any>>()

    fun <T: Any> registerSerializer( klass: KClass<T>, qualifiedName: String ) { ... }
    private fun getSerializerBySimpleClassName( className: String ): KSerializer<Any> { ... }
    private fun getSerializerByQualifiedName( qualifiedName: String ): KSerializer<Any> { ... }
}
```

Subsequently, in `save()` and `load()` serializers are retrieved from the map of registered serializers instead of `serializerBySerialDescClassname<Any>(klassName, input.context)` which is the only call which does not work for JS since it relies on retrieving the fully qualified name which cannot be retrieved due to JS reflection limitations.

This serializer can be used as follows [(full examples in unit tests)](https://github.com/cph-cachet/carp.core-kotlin/blob/js-serialization/carp.protocols.core/carp.protocols.core-common/src/test/dk/cachet/carp/protocols/domain/serialization/PolymorphicSerializerTest.kt).

```
@Serializable
internal class A( val a: String = "a" ) : BaseClass()
{
    companion object
    {
        init { PolymorphicSerializer.registerSerializer( A::class, "dk.cachet.carp.protocols.domain.serialization.PolymorphicSerializerTest.A" ) }
    }
}
```

For lists, the following serializer can be specified: `object PolymorphicArrayListSerializer : KSerializer<List<Any>> by ArrayListSerializer( PolymorphicSerializer )`

The primary limitation of this approach is that you cannot register classes with the same name. Less severe is the extra step of having to register serializers manually in any polymorph type. However, the big benefit is the same codebase can now be used to serialize from/to Java and JavaScript. After having looked into some JavaScript serialization libraries [which also do not support proper polymorph serialization](https://github.com/mobxjs/serializr/issues/65), I am quite pleased with this result, and believe an approach like this is much preferred (for maintainability/scalability) over trying to do something similar outside of Kotlin.

**Comment by sandwwraith** [comment]
#394 has this and it is included into `0.11.0` release.

**Comment by Whathecode** [comment]
Great! Is there a readme on how to use this yet? I can't seem to find it.

**Comment by Whathecode** [comment]
For those looking for information: registering polymorphic types needs to be done using `SerialModule` which is passed to the `Json` constructor. More info can be found here: https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/custom_serializers.md#registering-and-context

An example on how to initialize `SerialModule` using a builder to register a couple of polymorphic types can be found here: https://medium.com/@andreclassen1337/goodbye-runtimetypeadapterfactory-polymorphic-serialization-using-kotlinx-serialization-46a8cec36fdc

**Comment by pdvrieze** [comment]
One caveat here that has hit me. The lookup now uses the name property of the serialdescriptor instead of the class name (old behaviour). While the default value for this name is the type name, this can be overridden by specifying `@SerialName` on the type declaration. In that case, the serialization is not compatible anymore.
