### ISSUE TITLE
Make ListSerializer() a function on an object like serializer()

### ISSUE THREAD

**Issue by Syex** [Kotlin/kotlinx.serialization#1016]
**What is your use-case and why do you need this feature?**
Hey,

I just migrated to 1.0.0-RC and had to change my list serializations from `MyClass.serializer().list` to `ListSerializer(MyClass.serializer())`. I thought `ListSerializer` is a class and I need to create an instance of it, but it's actually a method, what's quite confusing.

I think this new solution is quite hard to find, if you don't know it exists.

**Describe the solution you'd like**
I'm wondering why it's not simply `MyClass.listSerializer()` or just like before `MyClass.serializer().list()`? You can add similar methods for `Sets` and `Maps`.  It's way more straight-forward to understand and is consistent with how you use the "default" serializer.

**Comment by tom5079** [comment]
I think the reason behind the change is to follow the philosophy of object-oriented programming.

`serializer.list` implies that the single object serializer has a list serializer as a member of it, which sounds somewhat weird.
`ListSerializer(serializer)` implies that the list serializer is containing a single object serializer, and it sounds more plausible.

> I thought ListSerializer is a class and I need to create an instance of it, but it's actually a method, what's quite confusing.

You could think of it as a class constructor, indeed it is.
```kotlin
public fun <T> ListSerializer(elementSerializer: KSerializer<T>): KSerializer<List<T>> =
    ArrayListSerializer(elementSerializer)
```
calling a class constructor and top-level method is no different in Kotlin so where is your confusion coming from?

**Comment by Syex** [comment]
Personally I think an extension function like
```
fun <T> KSerializer<T>.forLists() = ListSerializer(this)
or
fun List<T>.serializer() // if that's possible
```

would express the same, that you have a `ListSerializer` with a single serializer for lists,  but is way more easy to find by exploration. Just saying that this was the first thing I did after I saw from the migration that `serializer().list` is no longer available.

Also reading the code it's much more convenient that the object you're parsing from/to json is the first parameter and not `ListSerializer`.

> calling a class constructor and top-level method is no different in Kotlin so where is your confusion coming from?
well ok, convinced, just never saw that one before

After all I just wanted to give some feedback about the usage. If you folks don't agree then I'll just create my own extension function 😄

**Comment by tom5079** [comment]
Whoops, I think I might be spreading the misinformation here.
I'm not an official member of this project, I'm just a guy interested in this project 😅

**Comment by elizarov** [comment]
This change was done so that API to create custom serializers is as consistent between different serializers as we could make it. If you define `@Serializable class Box<T>(...)` and you want a serializer for `Box<MyClass>`, then you write `Box.serializer(MyClass.serializer()))`. Ideally, we'd love to have `List.serializer(MyClass.serializer())`, but we cannot easily make it so, so the `ListSerializer(MyClass.serializer())` syntax is the closest thing we can have. 

Keep in mind, that in Kotlin Serialization 1.4.0 you rarely need to create serializers yourself anyway. You can just write `format.encodeToXxx(data)` where `data` is of `List<MyClass>` type, and the appropriate serializer will be instantiated automatically. You can also use `serializer<List<MyClass>>()` if you need to fetch an instance of a serializer for a specific type in your code. 

Please, see more in this section of the docs: https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md

Does it help?

**Comment by Syex** [comment]
>  You can just write format.encodeToXxx(data) where data is of List<MyClass> type, and the appropriate serializer will be instantiated automatically

That's pretty neat. Seems for me then it was only a migration issue.

Thanks for your explanation, very helpful, closing it then 👍
