### ISSUE TITLE
Sealed class does not always work as described by documentation

### ISSUE THREAD

**Issue by TorRanfelt** [Kotlin/kotlinx.serialization#1055]
Using kotlin/js 1.4 and kotlinx-serialization-core 1.0.0-RC sealed class is not working in this example:

```
@Serializable
sealed class Foo

@Serializable
@SerialName("Bar")
class Bar : Foo()
```

```
                    val serializer = PolymorphicSerializer(Foo::class).unsafeCast<KSerializer<Foo>>()
                    jsonMapper.decodeFromString(serializer, responseBodyStr)
```

Foo is sealed yet the following yields the error "Polymorphic serializer was not found for class discriminator 'Bar'"

In order for this to work I have to add polymorphic for Foo to SerializerModule. That should not be necessary when Foo is sealed.

```
        val serverInterfaceModule = SerializersModule {
            polymorphic(ErrorResponse::class) {
                subclass(Foo::class)
           }
        }

        val jsonMapper = Json {
            serializersModule = serverInterfaceModule
        }
```

**Comment by qwwdfsad** [comment]
This is expected behaviour.
Please refer to the documentation of `PolymorphicSerializer`, this is the expected behaviour of polymorphic serializer.

In order to make your example work, it's enough to use `jsonMapper.decodeFromString(Foo.serializer(), responseBodyStr)` that works polymorphically and does not requires explicit registration.

Does it solve your use-case?

**Comment by TorRanfelt** [comment]
Thanks. That worked.

`PolymorphicSerializer(Foo::class).unsafeCast<KSerializer<Foo>>()`

We have used kotlinx.serialization for maybe 1.5 years so the above must have been necessary in an older version.
