### ISSUE TITLE
Compiler hangs indefinitely with sealed class

### ISSUE THREAD

**Issue by sjmueller** [Kotlin/kotlinx.serialization#1067]
I have a sealed class acting as an enum with associated values:

``` kotlin
@Serializable
sealed class RealtimeRouter(
    @Transient val channelEventName: String = "",
    @Transient val auth: AuthParamConfig = AuthParamConfig.auth
) {
    val token: String?
        get() = if (auth == AuthParamConfig.auth) { token } else { null }

    @Serializable class start(val lastFetchedAt: String?, val loadMembers: Boolean = false): RealtimeRouter("event.start")
    @Serializable class stop(): RealtimeRouter("event.stop")
    // About 20 more of these
}
```

Whenever I have the `@Serializable` on the nested class, compilation hangs indefinitely:

<img src="https://user-images.githubusercontent.com/29085/93014565-f723a880-f566-11ea-889e-c19fa4a9f833.png" width="400" />

What could be going wrong?

**Environment**
 - Kotlin version: 1.4
 - Library version: 1.0.0-RC
 - Kotlin platforms: Regular Android
 - Gradle version: [e.g. 4.10]
 - IDE version: Android Studio 4.2 Canary 10

**Comment by qwwdfsad** [comment]
Hi, I've tried to copy-paste your example (and filled `AuthParamConfig` with a dummy enum) and it seems to be compilable perfectly, so, unfortunately, I cannot reproduce your problem. Are you sure serialization plugin is a root cause?

Also, could you please either provide a reproducing project or post a stracktrace here?
You can find hang compiler process PID using `jps` command and then just dump it using `jstack $foundPid`

**Comment by sandwwraith** [comment]
Maybe #968 ?
