### ISSUE TITLE
decodeStructure swallows exceptions

### ISSUE THREAD

**Issue by jschneider** [Kotlin/kotlinx.serialization#1187]
Exceptions thrown within the decodeStructure block are swallowed.

This code:

```    
decoder.decodeStructure(descriptor) {
        TODO()
    }
```

throws an JsonDecodingException:
Unexpected JSON token at offset 1: Expected '}'

I assume the original exception is hidden, because the decoder tries to finish decoding the JSON object.

I strongly prefer to have the the original exception thrown.

**Comment by sandwwraith** [comment]
I think the problem happens because `decodeStructure` always tries to finish structure in finally block:

```
finally {
        composite.endStructure(descriptor)
    }
```

AFAIR, exceptions thrown from finally block have higher priority, so the original exception is lost. And JSON decoder can't find closing brace because body hasn't been decoded, hence 'expected }'.
