### ISSUE TITLE
Support transient read-only properties without default values

### ISSUE THREAD

**Issue by dkhalanskyjb** [Kotlin/kotlinx.serialization#1227]
I want the following code to work:
```kotlin
@Serializable
class A {
    @Transient
    val x: String
    
    init {
        x = "ok"
    }
}
```

This seems viable, as `x` being a `val` already implies that this value is bound to be initialized by the end of `init { ... }`, which is called by deserializers.

**What is your use-case and why do you need this feature?**

I wanted to mark these two properties as transient: https://github.com/Kotlin/kotlinx-datetime/blob/3af71d2e874592fc70282de441a09d024dcefb54/core/common/src/DateTimeUnit.kt#L17-L18

I was able to work around this issue by splitting the `init { ... }` code between the two properties: https://github.com/Kotlin/kotlinx-datetime/blob/16e0804a5dc41558bad7b189f3575109515d41d6/core/common/src/DateTimeUnit.kt#L22-L42 The resulting code is looks messy though.

**Describe the solution you'd like**

Detect if the annotated field is a `val`. If it is, allow it to be marked with `@Transient`.

**Comment by sangeetds** [comment]
Hi @sandwwraith. It looks like you may be looking into this issue. Please let us if there are any updates on this?

**Comment by sandwwraith** [comment]
No updates yet :(

**Comment by sandwwraith** [comment]
We are not going to support this case (at least for now). The reason is following:
Property can also be initialized from the constructor, which is __not__ called during the deserialization:

```kotlin
@Serializable
class A {
    @Transient
    val x: String // Will be not set after decodeFromString<A>()

    constructor(y: String) {
        x = "ok" + y
    }
}
```

Currently, the compiler plugin does not know whether the property was set in the constructor or in the init block. Perhaps sufficient inclusion of CFG into the serialization plugin checker would solve this, but the amount of such cases is quite marginal. There is also an easy workaround:

@Serializable
class A {
    @Transient
    val x: String = run {
        // do some computations...
        "ok"
    }
}
```
