### ISSUE TITLE
Consider making `KClass<T>.serializer()`, or an equivalent function, a non-internal API

### ISSUE THREAD

**Issue by rocketraman** [Kotlin/kotlinx.serialization#1228]
**What is your use-case and why do you need this feature?**

I was integrating kotlinx.serialization with Apache Beam by creating a `CustomCoder` (https://beam.apache.org/releases/javadoc/2.5.0/org/apache/beam/sdk/coders/CustomCoder.html).

I wanted to make a generic CustomCoder that worked for all `@Serializable` classes.

In order to do this, I had to pass in the `Class<T>` in the constructor, convert that to `KClass<T>` via the `.kotlin` reflection function, and call `.serializer()` on that to obtain the `KSerializer<T>` [1].

However, that requires usage of an internal API.

Alternatively, this approach works and does not use any public APIs, assuming `clazz` is the `Class<T>` of the @Serializable T, except that now we introduce an unchecked cast:

```
@Suppress("UNCHECKED_CAST")
val serializer = serializer(clazz.kotlin.starProjectedType) as KSerializer<T>
```

[1] Note, I could not construct my custom coder with `KSerializer<T>` or `KType` directly, as neither of those implement `java.io.Serializable`, and that causes Beam to throw a runtime `NotSerializable` exception.

**Describe the solution you'd like**

In order to make this use case possible, KType could implement `java.io.Serializable`, or `KClass<T>.serializable()` should be a public API, or an equivalent mechanism to obtain a serializable from a class definition is needed e.g. `serializer(KClass<T>)`.

**Comment by sandwwraith** [comment]
The KClass.serializer() is not the ideal way to use in an integration due to its limitations (can't work with lists/generics etc, see more in docs). More correct approach would be to use `serializer(java.lang.reflect.Type)`, which is currently experimental, but we are going to stabilize it in one of the future releases. j.l.r.Type, as well as KType, preserve generic information, in contrary to Class<*> and KClass<*>. The only downside is that unchecked cast from KSerializer<Any> is inevitable, because Type/KType do not have type arguments; but this cast should work correctly.

The KClass.serializer() function may be used, as per documentation, 'as a last-ditch resort' — when you can't provide full generic information. In that case, you can opt-in to using an internal serialization api.

**Comment by sandwwraith** [comment]
See also a discussion in #1210

**Comment by sandwwraith** [comment]
The `serializer(KType)` is now a stable function.
