### ISSUE TITLE
JS: SerializationException: Can't locate default serializer for class

### ISSUE THREAD

**Issue by BorzdeG** [Kotlin/kotlinx.serialization#128]
demo project: https://github.com/BorzdeG/samples-kotlin-subprojects/tree/kotlinx.serialization
sample class: https://github.com/BorzdeG/samples-kotlin-subprojects/blob/kotlinx.serialization/client-js/src/main/kotlin/demo/client/js/ClientJs.kt

run command: `./gradlew :client-js:jettyRun`
open in browser url: `http://localhost:8080`
open developer console:
```
> toString
ParentModel(s=test-js, data=DataOne(p0=ps))
> json
uncaught exception: SerializationException: Can't locate default serializer for class class ParentModel
```

**Comment by BorzdeG** [comment]
The problem is only in the JS serializer - there is no error serializer in Java: https://github.com/BorzdeG/samples-kotlin-subprojects/blob/kotlinx.serialization/client-jvm/src/main/kotlin/demo/client/jvm/ClientJvm.kt

**Comment by sandwwraith** [comment]
You forgot to apply `plugin<SerializationGradleSubplugin>()` in your `client-js/build.gradle.kts`

However, after this your code will not compile since you use `Any` in `ParentModel` and Polymorphic Serialization is not available on JS (since it's impossible to load class by name there). You can track #101 for updates on this.
