### ISSUE TITLE
KSerializer can produce invalid JSON

### ISSUE THREAD

**Issue by fkrauthan** [Kotlin/kotlinx.serialization#1296]
**Describe the bug**

**To Reproduce**
A dataSerializer like this for a sub type:

```kotlin
@Serializable(with = ValueSerializer::class)
data class Value <T> (val isSet: Boolean, val value: T?)

class ValueSerializer <T> (private val dataSerializer: KSerializer<T>) : KSerializer<Value<T>> {
    override val descriptor: SerialDescriptor = dataSerializer.descriptor
    override fun serialize(encoder: Encoder, value: Value<T>) {
        if (value.isSet) {
            if (value.value == null) {
                encoder.encodeNull()
            } else {
                dataSerializer.serialize(encoder, value.value!!)
            }
        }
    }
    override fun deserialize(decoder: Decoder) = TODO("Not implemented!")
}

data class TestObject(
  val test1: Value<String> = Value(true, "Hello World"),
  val test2: Value<String> = Value(false, null),
  val test3: Value<String> = Value(true, null),
)
```

Produces output like this when calling `println(Json.encodeToString(testObject))`:

```json
{"value1":"Hello World","value2":,"value3":null}
```

In this case the `value2` has `isSet` marked as `false` and is producing invalid JSON.

**Expected behavior**

The JSON should look like this:

```json
{"value1":"Hello World","value3":null}
```

**Workaround**
For some reason having an additional Serializer like this

```kotlin
class ValueClassSerializer <T : Any> (private val dataSerializer: KSerializer<T>) : JsonTransformingSerializer<T>(dataSerializer) {
    override fun transformSerialize(element: JsonElement): JsonElement =
        element.jsonObject
}
```

and calling `println(Json.encodeToString(ValueClassSerializer(TestClass.serializer()), testObject))` produces the correct output.

**Environment**
 - Kotlin version: 1.4.21
 - Library version: 1.0.1
 - Kotlin platforms: JVM
 - Gradle version: 6.8

**Comment by qwwdfsad** [comment]
Thanks for the self-contained report!

Unfortunately, it is not really a bug, but the thing we can do nothing about.
Let me explain why this is happening:

- The serializer starts serializing `TestObject`
- It sees its `test1` property, writes `"test1:"` to the output, then invokes `ValueSerializer.serialize` on the actual value of `test1`
- It sees its `test2` property, writes `", test2:"` to the output, then invokes `ValueSerializer.serialize` on the actual value of `test2`
- `ValueSerializer.serialize` **does nothing** for this value, leaving `", test2:"` dangling in the output
- Serializer proceeds to `test3`

Effectively, the serializer is not allowed to do nothing in its `serialize` method, but we do not have a mechanism to check that. And serializer of the property has no control over the outer serializer and cannot signal it "hey, do not write this property because I'm not going to encode it"

So in order to achieve your goal, you have to control this behaviour on the outer serializer level.

Workaround just works by accident :)
I'd suggest you use the following serializer:
```
class ValueSerializer<T>(private val dataSerializer: KSerializer<T>) : KSerializer<Value<T>> {
    override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor("Value", PrimitiveKind.STRING).nullable

    override fun serialize(encoder: Encoder, value: Value<T>) {
        encoder.encodeNullableSerializableValue(dataSerializer, value.value)
    }

    override fun deserialize(decoder: Decoder) = TODO("Not implemented!")
}
```

**Comment by fkrauthan** [comment]
Ah that makes sense. Maybe we can convert this into a feature request for a simple Entity filter that returns `true` or `false` for each potential Property and entity if it should be included. Signature could be something like:

`fun shouldInclude(obj: Any, field: KProperty, fieldValue: Any): Boolean`

**Comment by qwwdfsad** [comment]
Then I';; close the issue if you don't mind.

Regarding feature request -- sure, go ahead! No commitment that we will actually implement it, but it would be nice to see the demand from users and general idea
