### ISSUE TITLE
[JS] "Can't find a method to construct serializer for type {class_name}. Make sure this class is marked as @Serializable or provide serializer explicitly." but it is annotated with @Serializable!

### ISSUE THREAD

**Issue by lamba92** [Kotlin/kotlinx.serialization#1339]
A data class marked as `@Serializable` errors with:
```stacktrace
Can't find a method to construct serializer for type TelegramResponse. Make sure this class is marked as @Serializable or provide serializer explicitly.
```

**To Reproduce**
Clone [kotlingram](https://github.com/lamba92/kotlingram) and run `./gradlew :examples:js-bot:run`. You will need a bot token to do so, the `run` tasks injects in the environment all variables in `local.properties` from the root of the project. You can edit token and bot name [here](https://github.com/lamba92/kotlingram/blob/master/examples/js-bot/src/main/kotlin/com/github/lamba92/kotlingram/examples/jvm/Main.kt#L20-L21). To get a token contact the [botfather](https://t.me/botfather) on telegram.

The class in question is [`TelegramResponse`](https://github.com/lamba92/kotlingram/blob/master/api/core/src/commonMain/kotlin/com/github/lamba92/kotlingram/TelegramResponse.kt) and it works correctly when used from JVM.

**Expected behavior**
It should deserialize correctly the class.

**Environment**
 - Kotlin version: 1.4.30
 - Library version: 1.0.1
 - Kotlin platforms: JS
 - Gradle version: 6.8.2

**Comment by sandwwraith** [comment]
You haven't posted your stacktrace, but my wild guess that you're using JS Legacy compiler and since TelegramResponse is a generic class and you do not use `TelegramResponse.serializer()` explicitly, the exception comes out of a reified inline `serializer<T>()` function. Legacy JS platform has limitation on this function — it can't work with generic classes, so you likely need to specify `TelegramResponse.serializer()` explicitly, as error message says

**Comment by lamba92** [comment]
Yes sorry, here a build scan with the output: https://gradle.com/s/s76v76d3z7nai! The call is made by Ktor so I have no control over deserialization.

**Comment by lamba92** [comment]
Switching to new backend solved the issue!
