### ISSUE TITLE
ElementValueInput doesn't pass the descriptor and index to the read method

### ISSUE THREAD

**Issue by ansman** [Kotlin/kotlinx.serialization#135]
I'm curious as to why `ElementValueInput` strips out the descriptor and the index when reading values. This makes it impossible to read annotations for example since `Input` cannot be subclassed.

**Comment by sandwwraith** [comment]
Purpose of `ElementValueInput` is to split reading element key from element value. So, before reading each value, `readElement` is invoked and it has a descriptor. Do you have an example where it's insufficient?

**Comment by ansman** [comment]
Well, the problem is that when using libraries such as `Moshi` you can annotate properties with qualifiers to say that you want a custom serialization behavior for that property. As the library is written today I would need to store the desc received in `readElement` or `readBegin` and use that when reading values to figure out if a property is using a qualifier.

**Comment by ansman** [comment]
I also understand that you long term might want to use a custom serializer for this but currently we would need already have a bunch of custom json adapters in moshi that we want to reuse.

**Comment by pdvrieze** [comment]
@ansman What you are asking for is what the `TaggedInput` / `TaggedOutput` classes allow you to do. You need to override getTag which you can then put anything you want including the classDesc and index.

**Comment by ansman** [comment]
Sure, that works but it feels very clunky and quite slow. 
Say I want to access both the index and the descriptor from the `readXXX` methods, I would have to create a new object (say a pair) for every property read or written. On platforms such as Android allocating a bunch of smaller objects can be pretty bad for performance.

I don't really see why they are stripped in the first place, would there be any harm to passing that info along to the read methods? Or making `Input`/`Output` open for subclassing.

**Comment by pdvrieze** [comment]
I don't think that TaggedInput/TaggedOutput are really slow. Even if you could directly subclass KInput and KOutput (you can't because of an internal constructor). you would have to choose to either use the stack approach that TaggedInput/TaggedOutput uses or use a new instance for every element that you serialize.
What it does provide you is consistent behaviour for "primitive" serializers versus element serializers (when writing their primitive children - note that if you have a conversion serializer this will not hit the primitive serializer directly, even if the conversion is just handling nullability).

**Comment by ansman** [comment]
I'm not saying that TaggedInput/TaggedOutput themselves are slow but if I allocate a custom object in `getTag` that encapsulates the data I need my code will be inefficient on Android since I will allocate small objects for every property read/written.

I know I can't subclass `KInput`/`KOuput`, that was my point. How come it is not allowed? Currently the library feels very geared towards the use cases handled by the built in support (JSON, CBOR etc), but it isn't very flexible for supporting other solutions.

I understand the library shouldn't give you access to everything but creating completely custom inputs and outputs doesn't feel like a bad thing.

**Comment by pdvrieze** [comment]
@ansman Recent versions of Android have decent garbage collection you can probably get a way with it. Otherwise just maintain a pool of them and reuse as needed. I agree with you on making KInput/KOutput directly subclassable. Maybe the best solution would be to have serializers create/provide a schema. I've opened bug #137 to describe the kind of metadata I'd like to have available. If it includes loader/saver references (and those would be required to have a serialClassDesc property - generally they do as they are subclasses of KSerializer) this would make it possible to recursively inspect the types (be careful of loops).

Btw. if you use instance per element you could just store current field number and classDesc in the object itself (on getTag) and have getTag return Unit or the classdesc (which you have anyway).

**Comment by sandwwraith** [comment]
@ansman reasons behind having `KOutput` with internal constructor were that it has big amount of methods which are hard to understand. So library exposes `ElementValueOutput` and `TaggedOutput` in order to reduce count of methods you need to override and present two different approaches of working with metadata: key-valued and stacked.

**Comment by ansman** [comment]
Yeah, I'm not arguing against having the subclasses for ease of use but I see no point in locking `KInput` and `KOutput` down since it limits the flexibility and usability of the library.

**Comment by sandwwraith** [comment]
It seems to be a bit obsolete, since KInput/Output have been replaced with two interfaces each.
