### ISSUE TITLE
Allow creation of custom polymorphic descriptor

### ISSUE THREAD

**Issue by diesieben07** [Kotlin/kotlinx.serialization#1411]
**What is your use-case and why do you need this feature?**
I am using `JsonContentPolymorphicSerializer` to deserialize JSON similar to the following:
Either:
```json
{
  "$ref": "<some URI>"
}
```
or
```json
{
   "actual": "data"
}
```
I'd like to improve the default `descriptor` provided by `JsonContentPolymorphicSerializer`, similar to the one provided by `SealedClassSerializer`. However it is currently impossible to construct a `SerialDescriptor` other than `StructureKind.CLASS` or primitive without using the internal API `buildSerialDescriptor`, which states:
> If you end up using this builder, please file an issue with your use-case in kotlinx.serialization

**Describe the solution you'd like**
A `SerialDescriptor` builder for `PolymorphicKind.SEALED` similar to `buildSerialDescriptor`.

**Comment by sandwwraith** [comment]
Currently, SEALED class descriptor has a requirement to contain all possible variants descriptors. I assume you can fulfil this requirement, since you know what serializers you are going to use statically, so it's possible to use internal API to mimic [SealedClassSerializer's descriptor](https://github.com/Kotlin/kotlinx.serialization/blob/0e4e0e729f97df1844a266647c2c4786ed780b2f/core/commonMain/src/kotlinx/serialization/SealedSerializer.kt#L79).

Why do you need this exact `SEALED` kind? Are you using something like a schema generator? This kind is not used in a regular serialization for now

**Comment by diesieben07** [comment]
Yes, I know all the possible serializers statically.

> Why do you need this exact SEALED kind? Are you using something like a schema generator? This kind is not used in a regular serialization for now

Because `JsonContentPolymorphicSerializer` says you can do so [in its docs](https://kotlin.github.io/kotlinx.serialization/kotlinx-serialization-json/kotlinx-serialization-json/kotlinx.serialization.json/-json-content-polymorphic-serializer/index.html#kotlinx.serialization.json%2FJsonContentPolymorphicSerializer%2Fdescriptor%2F%23%2FPointingToDeclaration%2F). However there is no way to do so without using the internal `buildSerialDescriptor` API.
