### ISSUE TITLE
Rename decodeSequentially

### ISSUE THREAD

**Issue by sandwwraith** [Kotlin/kotlinx.serialization#1469]
Since it is a property, not an action, a verb `decode` is kinda misleading — no internal state of decoder is changed.

See https://github.com/Kotlin/kotlinx.serialization/pull/600#discussion_r627685869

**Comment by Dominaezzz** [comment]
Does this also mean that `decodeElementIndex` shouldn't change the state of the decoder?
Since `decodeSequentially` returning true means you don't have to (but can) call `decodeElementIndex`, which mean it doesn't modify any state. It just peeks at what index to call next.
(Although I understand the ship has long sailed with this method name)

**Comment by sandwwraith** [comment]
No, `decodeElementIndex` can modify the state. This is very useful for formats with random access — one can iterate index with additional checks, if necessary. See example in JsonTreeDecoder: https://github.com/Kotlin/kotlinx.serialization/blob/c0976fdf150ba479a5d0031596e8f94d55ce60f3/formats/json/commonMain/src/kotlinx/serialization/json/internal/TreeJsonDecoder.kt#L202

However, `decodeSequentially` returning `true` usually means that `decodeElementIndex` simply returns `index++`. For formats without sequential decoding logic may be more complicated and tied to the fact that `decodeElementIndex` is a mandatory call.

**Comment by sandwwraith** [comment]
After some consideration, we've decided not to rename it because it is huge breaking change for ecosystem (all compiled `@Serializable` classes call this method), and technically, this method is not prohibited from changing Decoder state.
