### ISSUE TITLE
Support for CSV 

### ISSUE THREAD

**Issue by StokeMasterJack** [Kotlin/kotlinx.serialization#1476]
It would be nice if kotlinx.serialization supported csv files/ Currently I am using jackson-dataformat-csv for this purpose:

[https://github.com/FasterXML/jackson-dataformat-csv](https://github.com/FasterXML/jackson-dataformat-csv)

**Comment by pdvrieze** [comment]
I had a quick look at the documentation. There is an old article [here](http://www.cowtowncoder.com/blog/archives/2012/03/entry_468.html) that is helpful - in particular the limitations section at the bottom. It points out that (as is obvious) complex column types don't work easily (you could do a bit with supporting different levels of separators rather than comma only).

Overall, the CSV format has significant limitations and challenges for serialization (it would mainly be nice for deserialization). I don't think that CSV is therefore a prime candidate for official support, but of course you can write your own format 😉 .

**Comment by hfhbd** [comment]
I created a simple CSV support but it has some limitations, ordered properties and no support for inner lists.
https://github.com/hfhbd/kotlinx-serialization-csv
It also supports Fixed Length Formats, with the same limitations.
