### ISSUE TITLE
Serializer of kind ENUM cannot be serialized polymorphically with class discriminator

### ISSUE THREAD

**Issue by P1NG2WIN** [Kotlin/kotlinx.serialization#1486]
**Describe the bug**
java.lang.IllegalArgumentException: Serializer for ChangeAlarmTypeRequest of kind ENUM cannot be serialized polymorphically with class discriminator

All subclasses of MethodExecuteCode  have this problem

**To Reproduce**
```
polymorphic(MethodExecuteCode::class) {
    subclass(MethodExecuteStateTypeCode::class)
    subclass(ChangeAlarmTypeRequest::class)
    subclass(IncidentMethodCode::class)
}


interface MethodExecuteCode

@Serializable
enum class MethodExecuteStateTypeCode: MethodExecuteCode {

    @SerialName("create") CREATE,
    @SerialName("enable") ENABLE,
    @SerialName("disable") DISABLE,
    @SerialName("delete") DELETE,

}

@Serializable
enum class ChangeAlarmTypeRequest : MethodExecuteCode {
    @SerialName("alarm") START,
    @SerialName("cancel") STOP,
    @SerialName("update") UPDATE
}

@Serializable
enum class IncidentMethodCode: MethodExecuteCode {

    @SerialName("accept") ACCEPT,
    @SerialName("reject") REJECT,

}

```
**Environment**
 - Kotlin version: 1.5.0
 - Library version: 1.2.1
 - Kotlin platforms: JVM Android
 - Gradle version: 7.0.0
 - Other relevant context: Java 8

**Comment by Whathecode** [comment]
As the error indicates, _"ENUM cannot be serialized polymorphically with class discriminator"_.

The reason for this is enums are serialized as a **primitive kind** by default. E.g., in the case of JSON it simply tries to output the `SerialName`. There is no JSON object to place the class discriminator, i.e., `{"type": "fully.qualified.Name"}` by default).

The good news is `kotlinx.serialization` is quite flexible and you can set up a custom serializer to work around this. This is why [I wrote a `PolymorphicEnumSerializer`](https://github.com/cph-cachet/carp.core-kotlin/blob/develop/carp.common/src/commonMain/kotlin/dk/cachet/carp/common/infrastructure/serialization/PolymorphicEnumSerializer.kt).

> A serializer which supports registering [Enum]s as subclasses in polymorphic serialization when class discriminators are used.
> When class discriminators are used, an enum is not encoded as a structure which the class discriminator can be added to.
> An exception is thrown when initializing [Json]: " "Serializer for <enum> of kind ENUM cannot be serialized polymorphically with class discriminator."
> This serializer encodes the enum as a structure with a single `value` holding the enum value.
>
> Use this serializer to register the enum in the serializers module, e.g.:
> `subclass( <enum>::class, PolymorphicEnumSerializer( <enum>.serializer() )`

**Comment by P1NG2WIN** [comment]
@Whathecode Actually, i dont want to have a class discriminator, the default enum serializer behaviour is really what i want 

e.g: 
```
@Serializable
class MethodExecute(@SerialName("code") val code: MethodExecuteCode? = null,) with ChangeAlarmTypeRequest.START must be {"code":"alarm"}

```
I tried to write my custom serializer based on your code by replacing `buildClassSerialDescriptor` with `PrimitiveSerialDescriptor` but I get similar primary error

**Comment by Whathecode** [comment]
> Actually, i dont want to have a class discriminator, the default enum serializer behaviour is really what i want

The `Json` encoder is configured to use a class discriminator by default for polymorphic serialization. The fact that you are getting that error message means that the `Json` encoder is configured as such (the alternative being _array polymorphism_ in which case `type` is specified as the first element of a two-element array).

A class discriminator _needs_ to be added in order to be able to deserialize polymorphic type (`MethodExecuteCode` is polymorphic), unless you are using the `Json` encoder and you set up a custom [`JsonContentPolymorphicSerializer`](https://kotlin.github.io/kotlinx.serialization/kotlinx-serialization-json/kotlinx-serialization-json/kotlinx.serialization.json/-json-content-polymorphic-serializer/index.html).

Think of it this way: how does the deserializer know to initialize `ChangeAlarmTypeRequest` based on `{"code":"alarm"}`? E.g., what if there is also an `alarm` in `IncidentMethodCode`? Should it deserialize as `IncidentMethodCode.ALARM` or as `ChangeAlarmTypeRequest.START`?

The `JsonContentPolymorphicSerializer` allows you to _based on the content_ (e.g. "alarm") select the serializer (e.g. `IncidentMethodCode.serializer()`). But, you'd only be able to implement that logic as a two-way conversion if you can uniformly determine based on content which serializer to use. Once you can do that, the type information is irrelevant. But, by default the type information is added because that's a big assumption and requires custom serialization logic.

**Comment by P1NG2WIN** [comment]
@Whathecode I don't need to deserialize this json. It will go to the server
