### ISSUE TITLE
Serialize object with field

### ISSUE THREAD

**Issue by P1NG2WIN** [Kotlin/kotlinx.serialization#1499]
[Even if object has properties, they are not serialized.](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/polymorphism.md#objects)  Why? 

```
@kotlinx.serialization.Serializable
sealed class ObservePublisherParams(
    @SerialName("type") val responseType: ResponseType
): java.io.Serializable {

    @Serializable
    enum class ResponseType {
        @SerialName("notify") NOTIFY,
        @SerialName("object") OBJECT,
        @SerialName("mixed") MIXED, //NOTIFY + OBJECT
        @SerialName("hook") HOOK
    }

    @Serializable
    object NotifyParams: ObservePublisherParams(ResponseType.NOTIFY)

    @Serializable
    object ObjectParams: ObservePublisherParams(ResponseType.OBJECT)

    @Serializable
    object MixedParams: ObservePublisherParams(ResponseType.MIXED)

    @Serializable
    class HookParams(
        @SerialName("hook") val params: Params
    ): ObservePublisherParams(ResponseType.HOOK) {

        @Serializable
        class Params(
            @SerialName("path") val path: String,
            @SerialName("payload") val payload: String? = null,
        )

        override fun toString(): String {
            return "HookParams(params=$params)"
        }
    }

}
```
```
class ObservePathRequest(
    @SerialName("publisher") val publisher: ObservePublisher,
    @SerialName("params") val params: ObservePublisherParams? = null,
    @SerialName("filter") val filter: ObservePublisherFilter? = null,
)
```

When i serialize for example ObjectParams i expect `"params": {"type": "object"}` but get `"params": {}`

**Comment by shanshin** [comment]
`Even if object has properties, they are not serialized.`
see https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/builtin-classes.md#unit-and-singleton-objects

To get a JSON like `"params": {"type": "object"}` you need to use polymorphic serialization.
```
@kotlinx.serialization.Serializable
sealed class ObservePublisherParams(
    @SerialName("type") val responseType: ResponseType
): java.io.Serializable {

    @Serializable
    enum class ResponseType {
        NOTIFY,
         OBJECT,
         MIXED, //NOTIFY + OBJECT
         HOOK
    }

    @SerialName("notify")
    @Serializable
    object NotifyParams: ObservePublisherParams(ResponseType.NOTIFY)

    @SerialName("object")
    @Serializable
    object ObjectParams: ObservePublisherParams(ResponseType.OBJECT)

    @SerialName("mixed")
    @Serializable
    object MixedParams: ObservePublisherParams(ResponseType.MIXED)

    @SerialName("hook")
    @Serializable
    class HookParams(
        @SerialName("hook") val params: Params
    ): ObservePublisherParams(ResponseType.HOOK) {

        @Serializable
        class Params(
            @SerialName("path") val path: String,
            @SerialName("payload") val payload: String? = null,
        )

        override fun toString(): String {
            return "HookParams(params=$params)"
        }
    }
}
```

When serialize as root 
`Json.encodeToString(ObservePublisherParams.serializer(), ObservePublisherParams.ObjectParams)` gives `{"type":"object"}`.

When as a property
```
@Serializable
data class Container(val params: ObservePublisherParams)

Json.encodeToString(Container(ObservePublisherParams.ObjectParams))
```
gives `{"params":{"type":"object"}}`


Another way is to write custom serializer.

**Comment by P1NG2WIN** [comment]
> To get a JSON like `"params": {"type": "object"}` you need to use polymorphic serialization.

I think `type` has confused you. `type` does not come from class discriminator, it's an api field. After the sealed class code, I gave an example of an object in which the sealed class is used, and the result of its parsing.

**Comment by Whathecode** [comment]
> Even if object has properties, they are not serialized.

Because all you need to reconstruct it is its type. It's a singleton. I.e., if you know what you are serializing/deserializing, there is nothing to serialize.

**Comment by prog110** [comment]
@Whathecode Since the state of Singleton changes during the lifetime of the object, which one would want to serialize & deserialize even if its a single instance, was there a reason specified why singletons (`object`) are serialized with no properties (even if they have backing fields)?

In the [documentation](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/builtin-classes.md#unit-and-singleton-objects), it states

> Conceptually, a singleton is a class with only one instance, meaning that state does not define the object, but the object defines its state. 

This is not true. Singleton's state changes during the lifetime of the object (just like any non-singleton object). So, to me, the reasoning sounds flawed.

**Comment by pdvrieze** [comment]
@prog110 The fundamental problem is due to two different reasons for which an object is serialized/deserialized:
- To save/restore the singleton state. In such case it is clearly desirable to store the contents of the singleton.
- To refer to the object in related content. For example where it replaces enums (e.g. object children of sealed parents).

Then it should be noted that the latter is probably more spread out in a code base, as well as harder to deal with in terms of getting the effect if the behaviour for objects is opposite.

Implementation wise, generated serializers do not work on objects as generated serializers work by creating new instances (mostly) using a generated constructor (it may call the default one if it that is correct). Objects cannot be such instantiated, but instead need to have their state updated according to the data passed in. This cannot reliably work in all cases except when it does introspection/access hackery that does not work cross platform.

Currently the semantics are the way they are. It is not realistic to change them as it would be a very significant semantic break with existing behaviour. The solution:
- write a custom serializer
- have a "configuration" class that you either store in the singleton or update it with
- avoid using mutable singletons for the usual reasons
