### ISSUE TITLE
Error trying to decode literal String "null" in 1.2.2

### ISSUE THREAD

**Issue by bsimon36** [Kotlin/kotlinx.serialization#1600]
**Describe the bug**
Attempting to decode json with String value of "null" throws:

Exception in thread "main" kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 13: Unexpected 'null' value instead of string literal

**To Reproduce**

@Serializable
data class Test(val str: String)

JSON.decodeFromString<Test>("{\"str\":\"null\"}")

**Expected behavior**
No error, should decode to Test("null")

**Environment**
 - Kotlin version: 1.5.20
 - Library version: 1.2.2
 - Kotlin platforms: [e.g. JVM, JS, Native or their combinations]
 - Gradle version: [e.g. 4.10]
 - IDE version (if bug is related to the IDE) [e.g. IntellijIDEA 2019.1, Android Studio 3.4]
 - Other relevant context [e.g. OS version, JRE version, ... ]

**Comment by qwwdfsad** [comment]
Affects only `isLenient = true` json instances

**Comment by ajhuntsman** [comment]
I just ran into this bug when trying to deserialize a JSON file that has translated content between German and English.

As it turns out, "null" is the German word for the English word "zero".

Attention Germany: I'm a big fan of Hefeweizen and schnitzel, but you may want to look into this in all your software.

**Comment by Saxintosh** [comment]
Please... fix this bug ASAP! 🙏
