### ISSUE TITLE
Deserializing object with default value from another module fails (regression in Kotlin 1.5.2x)

### ISSUE THREAD

**Issue by altavir** [Kotlin/kotlinx.serialization#1602]
**Describe the bug**

When the serializable class has an ancestor with a default value in another module. Its deserialization with missing value fails.

**To Reproduce**
Here is the reproducer: https://github.com/altavir/serialization-bug-demo

**Expected behavior**

Should work!
Worked fine in 1.5.10

**Environment**
 - Kotlin version: 1.5.21
 - Library version: 1.2.2
 - Kotlin platforms: Any

**Comment by naftalmm** [comment]
It works in 1.5.10 because serialization (erroneously) encodes defaults, so result of `val string = Json.encodeToString(Demo1.serializer(), Demo1())` is `{"optional":null}`, so when `string` is passed for deserialization, there is actually no missing fields.

Deserialization of hardcoded empty JSON doesn't work in both 1.5.10 and 1.5.21:

`val res = Json.decodeFromString(Demo1.serializer(), "{}")` //Exception in thread "main" kotlinx.serialization.MissingFieldException: Field 'optional' is required for type with serial name 'Demo1', but it was missing

**Comment by naftalmm** [comment]
The debugger shows that plugin-generated descriptor has incorrect `elementsOptionality` field:

![image](https://user-images.githubusercontent.com/10289217/128306655-a371849c-30dc-4c43-b60b-ddbf96f5b7b6.png)

But I don't understand why this happens in runtime, decompiler shows that generated bytecode is correct and the value should be `true`:
![image](https://user-images.githubusercontent.com/10289217/128307373-9c6a023f-9405-4f7c-95a1-5662e9c29d0a.png)

**Comment by burhankhanzada** [comment]
downgrading kotlin version to `1.5.0` does fix wired behaviour that some times its works and some times it doesn't but still if I have `A` serializable class and a `B` class extend from `A` in `main` source and then use it to extend class `C` from `B` in `test` source of in another `module` its till giving error `missing optional field`

**Comment by ptsiogas** [comment]
@altavir is there a target day for a solution? It is really blocking us and downgrading to 1.5.10 is not an option anymore.

**Comment by altavir** [comment]
@ptsiogas I am not the serialization developer. I am waiting for it myself.

**Comment by sandwwraith** [comment]
Seems related to #1481

**Comment by altavir** [comment]
@sandwwraith I do not see the relation. This one is solidly reproduced with cache clean and does not have any polymorphic kinds. By the way, my workaround (inheriting and re-defining the field) seems to stop working on 1.5.30-RC. So it becomes a blocker.
