### ISSUE TITLE
StackOverflowError when parsing deep JSON with arrays

### ISSUE THREAD

**Issue by tchernykh** [Kotlin/kotlinx.serialization#1703]
**Describe the bug**
Follow up to #1594

JsonTreeReader class of kotlinx-serialization-json library uses recursion to parse JSON which causes StackOverflowError when JSON is very deep. It was fixed for objects but the issue is still there for arrays.

**To Reproduce**
```Kotlin
var json = """{ "a": [%]}"""
repeat (12) {
    json = json.replace("%", json)
}
json = json.replace("%", "")
Json.parseToJsonElement(json)
```

**Expected behavior**
Json parsed without crashes

**Environment**
 - Kotlin version: 1.5.30
 - Library version: 1.3.0
 - Kotlin platforms: JVM
 - Gradle version: 7.0.2

**Comment by qwwdfsad** [comment]
It was deliberately fixed for objects only: the change is quite cumbersome and obfuscates the support of the library itself, while the use-case is pretty narrow and unique (e.g. other frameworks just don't support that).

The existing solution "collapses" stackframes for `JsonObject`, so the only way to reproduce the issue is to have a really deep nesting of `array -> array ... -> array` or `object -> array -> object -> array -> .... -> object -> array`

We even left a comment in the code
>This case is quite rare and specific, so more complex nestings (e.g. through the chain of JsonArray and JsonElement) are not supported.

So this bug is unlikely to be fixed unless there is a real production-usage-guided use-case for that.
