### ISSUE TITLE
Make JsonElement @Serializable

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.serialization#175]
After #86 

It would help to avoid features re-implementing: strict mode, input validation, prettification of the output

**Comment by altavir** [comment]
I would like to support the feature and also ask for the implementation as example. I seem to be completely stuck with trying to create custom (or standard) implementation to the recurrent structure which is similar to JSON. I can easily translate my structure to JsonObjectand back but it is not serializeable itself.

Also if I could see `Serializator` for JSON, I could probably easily implement similar one for my structure.

**Comment by altavir** [comment]
I've already found it and trying to trying to figure it out right now. But it has complicated architecture which is hard to figure without documentation.

**Comment by altavir** [comment]
I spent two days trying to do just that. There are no problems implementing serializer. It is fairly straight forward and generates correct JSON (though some kind of DSL would be welcome like discussed in slack).
The problem is with deserialization. The serialization framework is specialized to work with the fixed templates, so there does not seem to be easy way to find out if you reading value or an object from JSON during the process. Even reading simple key-value pair with basic deserializer is hard. There are some helper classes in that are used in `JsonTreeMapper `, but as I already said, it is impossible for me to untangle architecture this complicated without documentation in a limited time I have and most of them are private, so I can't use them as is.

By the way, returning to the initial issue, right now I can't even transform `JsonObject` to `String` and back (all input and output classes are internal and private) which is frustrating.

**Comment by altavir** [comment]
The problem with `String` parsing seems to be solved with 5ed5f8c.
