### ISSUE TITLE
Serializers for java.time.*

### ISSUE THREAD

**Issue by rrva** [Kotlin/kotlinx.serialization#1806]
**What is your use-case and why do you need this feature?**

We use a lot of `java.time.OffsetDateTime` which it is a bit cumbersome to have to annotate separately with a custom serializer like `@Serializable(KOffsetDateTimeSerializer::class)`. 

**Describe the solution you'd like**

It would be useful to have a special `org.jetbrains.kotlinx:kotlinx-serialization-jvmtime` dependency which automatically adds serializers to handle some very common classes from the  java8 java.time module.

**Comment by sandwwraith** [comment]
Currently, it is possible only with `@file:UseSerializers` annotation. For module-wide options / auto-including from dependency, there is a separate issue: https://github.com/Kotlin/kotlinx.serialization/issues/507

**Comment by cvmocanu** [comment]
I don't understand why this ticket was closed. _"Currently, it is possible only with `@file:UseSerializers` annotation"_ is another way of saying _"we acknowledge that this is a problem"_, so the ticket should not have been closed.

Please reopen.

Core Java classes should be supported by default - either in the core or in a separate gradle module, dedicated to java time classes.

**Comment by pdvrieze** [comment]
@cvmocanu It was closed because the issue is a general issue with having a unified way of linking serializers to external types that do not have them. That issue is fundamentally unrelated to the time types. This issue is a duplicate of that issue #507.

As a separate point, the best workaround at the moment is likely to use type aliasses that have the desired serializer annotated on the right side. For example (you can use shorter names):
```kotlin
typealias EpochSerializableInstant=@Serializable(InstantAsEpochLongSerializer::class) Instant
```

As to the point of core java classes, this is easier said than done, and might not work in a straightforward way at all.

Overall, take a look at #507 as that is the issue that collects the discussion.
