### ISSUE TITLE
It is hoped that a convenient function can be added to the plug-in

### ISSUE THREAD

**Issue by ltttttttttttt** [Kotlin/kotlinx.serialization#1808]
It is hoped that a convenient function can be added to the plug-in
**What is your use-case and why do you need this feature?**
More convenient
**Describe the solution you'd like**
Add a configuration item in the plug-in to configure a folder so that the kotlin class in the folder can be serialized automatically without manual annotation.
Because it's easy to forget to annotate manually, resulting in a crash.

**Comment by sandwwraith** [comment]
We do not have any plan to implicitly add `@Serializable` annotation to classes in certain packages or folders for several reasons:
First, making assumptions about the code will be much harder in such a setup. Reviewers or just other people on the team — who read code — may not understand whether a particular class was supposed to be serializable or not, and whether certain restrictions of serializable classes (such as 'constructor parameters must be properties') may apply.

Second, for security reasons: it is too easy to expose internal classes with sensitive data if they would be automatically serializable.

Third, compiler plugin heavily relies on annotation markings and forcing it to scan whole package may slow down resolve & compilation.

**Comment by rrva** [comment]
Regarding reviewing: If you restrict the implicit @Serializable only to data classes I do not think the reviewer argument holds. In 99.9% of all cases data classes should be serializable already without any changes. If you use some non-standard way to define a data class which makes it not serializable than it is perhaps better to use a regular class. This should be obvious to all reviewers already.

**Comment by rrva** [comment]
I think it will be good for adoption of kotlinx.serialization if you can just switch between different serializers quickly without annotating. Then it would be a drop-in replacement for handling data classes which previously were serialized by for example Jackson.

**Comment by RuiLoureiro** [comment]
Another use case for this feature is to be able to use kotlinx.serialization with generated data classes (in my case I'm using [json-kotlin-schema-codegen](json-kotlin-schema-codegen)). Currently, you need to add the `@Serialization` annotation to the generated data classes, and that gets overwritten every time you re-generate the code.

**Comment by rrva** [comment]
Another use case which calls for annotation-free serialization is when you do not have access to the source code or cannot easily rebuild the sources because the classes you want to serialize are part of some third-party component.

**Comment by qwwdfsad** [comment]
I'll try to answer all the points at once.

> If you restrict the implicit @serializable only to data classes I do not think the reviewer argument holds. In 99.9% of all cases data classes should be serializable already without any changes

The solution has multiple downsides: it can drastically blow up the bytecode size (-> if the package has a lot of data classes not intended to be serialized), it exposes classes as serializable when there was no intention to serialize them in the first place and it may provide a lot of compiler errors -- it's enough for data-class to reference non-data class or Java type and the whole project no longer compiles.

Apart from that, there are reasons not to use data classes -- [binary compatibility ](https://jakewharton.com/public-api-challenges-in-kotlin/), avoiding `copy()` generation, inheritance of the classes and so on. This is not the restriction we want to enforce in the serialization.

>As for security, this is also a bit of a weak argument. 

Sensitive classes are not only ones that handle/store sensitive strings, but also ones that perform *sensitive actions*, for example, bytecode manipulation or class-loading. It's easy to argue that "we don't do that in our code-base", but the [whole family](https://github.com/GrrrDog/Java-Deserialization-Cheat-Sheet) of zero-days will speak for themselves. Log4Shel is also a good example of that, though not directly related to serialization, only to the underlying mechanism of the exploit. In fact, the issue is so intense, that it first was attempted to [be fixed](https://openjdk.java.net/jeps/290) the serialization in Java and later it was decided [to fully rewrite the serialization](https://cr.openjdk.java.net/~briangoetz/amber/serialization.html) which is a unique occasion for 20+ years old feature in Java.


>I think it will be good for adoption of kotlinx.serialization if you can just switch between different serializers quickly without annotating. Then it would be a drop-in replacement for handling data classes which previously were serialized by for example Jackson.

It's a good use-case, but it was never our goal. Especially for multiplatform, where there is no reflection.
By anecdotical evidence, this is not the case for regular reflection-based frameworks as well -- the typical enterprise codebase relies on framework-specific annotations and custom serialization mechanisms so heavily, that it's never possible to *just* switch the framework. 

Yes, it may be the case for a small app with dozen of serializable classes, but in such cases, it doesn't worth putting the whole design of the `kotlinx.serialization` in jeopardy.

>Another use case which calls for annotation-free serialization is when you do not have access to the source code or cannot easily rebuild the sources because the classes you want to serialize are part of some third-party component.

This is a use-case we are aiming to solve. We're supporting external serializers for exactly this purpose.
E.g. you can write 

```
@Serializer(forClass = ClassFromAnotherLibrary::class)
object ClassFromAnotherLibrarySerializer
```

and everything will work

**Comment by elizarov** [comment]
Since the question still comes up a bit, let me give some hope to everyone who is interested in this issue. The statement that "In 99.9% of all cases data classes should be serializable already without any changes" is indeed true, but data classes are still not restrictive enough in the langauge to be serializable by default. However, we do have a language precedent where `enum class` is "serializable by default" without having to mark it with `@Serializable` annotation. So, in the future, when we walk down the road of better support for value classes in the language (see https://github.com/Kotlin/KEEP/blob/master/notes/value-classes.md) we will look into having such a restricted subset of value classes in the language which is always safe to be serialized by default. Tentatively (internally), we call them "const classes" as the other use-case of "classes that can be safely serialized and deserialized" is that they can be computed in compile-time and can be stored in `const val` properties by the compiler (as they will have a way to be serialized).

**Comment by nealeu** [comment]
> Second, for security reasons: it is too easy to expose internal classes with sensitive data if they would be automatically serializable.

So what about the toString() implementation of data classes then?  Shouldn't that be removed given this is an easy way of getting data into a log entry as was the case with Log4Shell?

**Comment by sandwwraith** [comment]
@nealeu You don't send your logs in your API responses, do you? Besides, you can override `.toString()`, while there's no such thing as `@NotSerializable`.

Anyway, this is a real problem too, and different people try different mitigations, see for example https://github.com/ZacSweers/redacted-compiler-plugin

**Comment by nealeu** [comment]
@sandwwraith I was referring to the Log4Shell vuln of potentially being able to use logging infrastructure to send out sensitive data which `toString()` would make far easier to dump.

My underlying point that `toString()` is exactly a method that serializes a `data class` to a string, and therefore should be viewed as equally vulnerable.

In fact (and ... that plugin is a good example of the real problem), the `toString()` default implementation of data classes is far worse a problem than doing the same in kotlinx.serialization because there are so many places where `toString()` will be called if an object is found where a string is expected.

**Comment by sandwwraith** [comment]
Yeah, and that's why we shouldn't introduce more potentially problematic features

**Comment by sdfgsdfgd** [comment]
for 2 odd excuses you have listed, community have mentioned 10-15 different, VERY VALID use cases, including being able to use natively generated (apollo or whatever) data classes straight out of the box. 

Thousands of use cases like this one. 

One must be blind to ignore this. Just implement this feature and let us replace all other libraries with kotlinx.serialization so we can FINALLY HAVE A MULTI MODULE DEPENDENCY that does the job properly, so we don't have to use anything else like Gson() anymore !
