### ISSUE TITLE
AbstractMethodError with polymorphicDefaultDeserializer

### ISSUE THREAD

**Issue by headsvk** [Kotlin/kotlinx.serialization#1835]
**Describe the bug**

Initializing `Json` fails at runtime with:
```
java.lang.AbstractMethodError: abstract method "void kotlinx.serialization.modules.SerializersModuleCollector.polymorphicDefaultDeserializer(kotlin.reflect.KClass, kotlin.jvm.functions.Function1)"
at kotlinx.serialization.modules.SerialModuleImpl.dumpTo(SerializersModule.kt:195)
```

**To Reproduce**
Setup Json in the following way for polymorphic deserialization:
```
val json = Json {
        classDiscriminator = "error"
        serializersModule = SerializersModule {
            polymorphicDefault(ErrorResponse::class) {
                DefaultErrorResponse.serializer()
            }
        }
}  

@Serializable
internal sealed class ErrorResponse {
   abstract val error: String,
}

@Serializable
internal data class DefaultErrorResponse {
   override val error: String,
} : ErrorResponse()

```
Reproduced when running instrumented Android tests on API 30 emulator.

**Expected behavior**
`Json` is initialized successfully like with library version 1.3.1.

**Environment**
 - Kotlin version: 1.6.10
 - Library version: 1.3.2
 - Kotlin platforms: JVM
 - Gradle version: 7.3.3
 - JRE version: 11
 - R8 version: disabled

**Comment by sandwwraith** [comment]
Hi, 
I'm unable to reproduce this issue neither in plain JVM nor Android emulator.
From what I see, I can suggest that this issue may be caused by inconsistency between versions of kotlinx-serialization-core and kotlinx-serialization-json — this method was introduced in core:1.3.2, so if json is of 1.3.1 version or less, it can't implement it. Can you re-check your dependencies, please?
