### ISSUE TITLE
Add type safety (like Moshi does)

### ISSUE THREAD

**Issue by cedricloneux** [Kotlin/kotlinx.serialization#1859]
Decoding a json string to get an object should return an optionnal. Here is an exemple of type safety return using Moshi

```kotlin
val adapter: JsonAdapter<Station> = Moshi.Builder().build().adapter(Station::class.java)
                adapter.fromJson(json)?.let {
                    StationDetail(navController = navController, station = it)
                }
```

**Comment by JakeWharton** [comment]
All `JsonAdapter`s in Moshi technically return `@Nullable` because it is written in Java. That does not magically mean `null` will always be used to signal something. Your code as written will (probably) never actually return `null` from the `fromJson` method. You would have to call `nullable()` on the `JsonAdapter` first and all that does is support explicit `null` literals in the JSON. If there is a problem with the JSON matching the expected structure Moshi will throw a `JsonDataException` and if there is a transport problem (reading the bytes from the stream) it will throw an `IOException`.

**Comment by sandwwraith** [comment]
I don't think we should return `null` in any failure case. JSON problems can be of wide variety and severity, and exception message often contains more valuable information than just `null`. In an ideal exceptionless FP world we probably should do `Either<JsonParsingError, T>`, but I think in most of the cases `runCatching { json.decodeFromString(...) }` should suffice for now.
