### ISSUE TITLE
[Question] Exception in case of the types of the values of mapOf is not same

### ISSUE THREAD

**Issue by yamatakau08** [Kotlin/kotlinx.serialization#1867]
```
@Serializable
data class Params<T>(val params: List<T>)

inline fun <reified T> xpost(params: List<T>) {
    val x = Params(params)
    Log.d("TEST","xpost x : $x")

    val y = Json.encodeToString(x)
    Log.d("TEST","xpost Json.encodeToString : $y")
}
```

When the types of the value of mapOf are same,
```
val rparams70 = listOf(mapOf("settings" to listOf(mapOf("value" to "2", "target" to "color")))) // pass
xpost(rparams70)
```
works fine.

On the other hand ,when the types of the value of mapOf are not same,
```
val rparams71 = listOf(mapOf("settings" to listOf(mapOf("value" to 2  , "target" to "color")))) // Exception
xpost(rparams71)
```

in xpost func, Params Serialization has Exception.
```
Caused by: kotlinx.serialization.SerializationException: Serializer for class 'Any' is not found.
    Mark the class as @Serializable or provide the serializer explicitly.
```

Could you teach me how to avoid the Exception?

Environment
Android Studio Bumblebee 2021.1.1
build.gradle (Project: My_Application) classpath "org.jetbrains.kotlin:kotlin-serialization:1.6.10"
build.gradle (Module: My_Application.app) implementation 'org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.2'

**Comment by sandwwraith** [comment]
The thing is, in the second case, you're actually serializing `Map<String, Any>` instead of `Map<String, String>`. We do not support serializing arbitrary `Any` even it's only either String or Number because it is unnatural for Kotlin's type safety. Try using `JsonObject` instead. On details about that matter, check the issue with a detailed explanation: https://github.com/Kotlin/kotlinx.serialization/issues/296
