### ISSUE TITLE
Allow Custom Serializers to access JSON option

### ISSUE THREAD

**Issue by electricjones** [Kotlin/kotlinx.serialization#191]
This may already be possible, but I didn't see it in any documentation, and haven't been able to make it work. 

When writing a Custom Serializer, specifically the `save(output, obj)` method, is it possible to know options that were passed into the `JSON` object? Specifically `unquoted`, `indented`, `nonstrict`, the context, etc?

When creating a custom serializer for a class that is used as a property, it would be nice to know if the custom serializer should include line breaks, quotes, etc...

**Comment by sandwwraith** [comment]
You can try to downcast `output` to `JSON.JsonOutput`, but it will mean that your object can be saved only by json, not by protobuf and other formats. However, options you mentioned there are private (except context). They can be leveraged to public, but you don't need to bother about them. Because serializer is a common abstraction over various formats, it should not think about quotes and etc. Current implementation of JSON handles them automatically according to its current settings and does not provide API to manually insert separators.
