### ISSUE TITLE
suspending serialize/deserialize

### ISSUE THREAD

**Issue by benkuly** [Kotlin/kotlinx.serialization#1934]
I need to make a database/cache call within `deserialize` to determine which `DeserializationStrategy` should be used depending on a field value. This is not possible, because serialize/deserialize is blocking.

**Comment by pdvrieze** [comment]
This is a really exceptional case. Normally it would be very much against expectations if serialization/deserialization fails because a database is not available. As to making these suspend functions, it would make the entire library suspendable (and incompatible). It is probably better to have a parallel suspendable library, but given the issues with the context it may be better to just use regular threads/waiting to deal with this database/cache.

**Comment by sandwwraith** [comment]
During the initial library design phase, we were considering making all serialization functions suspendable. After the evaluation, we concluded that adding the state machine to every function like `decodeInt()`, etc would dramatically slow down whole process because of the overhead. So I doubt that suspending serialization would make a lot of sense.

**Comment by sandwwraith** [comment]
You should use `withContext(Dispatchers.IO)` for blocking IO and deserialization. I was referring to the case if `decodeFromString` is a `suspend` function.
