### ISSUE TITLE
HDF5? 

### ISSUE THREAD

**Issue by mgroth0** [Kotlin/kotlinx.serialization#1993]
I did a search for HDF5 and found nothing in this repository.

I have a few questions:

- Are there any thoughts on adding support for HDF5?
- How difficult would it be to make a custom serializer for this format?
- What supported format is most similar to HDF5?

**Comment by pdvrieze** [comment]
> - Are there any thoughts on adding support for HDF5?
It is not a format that would be part of the core library, but a custom format is possible.

> - How difficult would it be to make a custom serializer for this format?
This depends on your use case and requirements. HDF5 appears to be quite complex dataset, and it has an implicit schema (in other words, there are multiple ways to store the same way and the encoder somehow needs to decide). Another challenge is that the format supports all kinds of rich datatypes (like images) that are not directly supported by the serialization library (you can support them/special case them).

Overall what I see as very challenging is to support reading generic HDF5 data, or data generated by another application. 

> - What supported format is most similar to HDF5?
It depends very much as to what you want. However, it seems that protocol buffers may be able to provide what you need, but without further understanding on what you need it is hard to be more specific.

**Comment by altavir** [comment]
Our team is currently working on some interactions with HDF5. HDF is a very complex format and there is only one full implementation (in C++ as usual). Even supporting its features is hard. Even if we limit ourselves to only a small subset, I can't see any benefits of using serialization for it since it aimed mostly at nd-array data and not for generic structures. I think it makes sense to discuss it at `science` channel at kotl.in/slack.

**Comment by qwwdfsad** [comment]
Taking into account the overall complexity and low demand, closing it won't fix.

We will gladly accept it as a [community-supported format](https://github.com/Kotlin/kotlinx.serialization/tree/master/formats#other-community-supported-formats) though!
