### ISSUE TITLE
API to help with JSON transformations

### ISSUE THREAD

**Issue by Whathecode** [Kotlin/kotlinx.serialization#2045]
**What is your use-case and why do you need this feature?**

As part of versioning an API which uses `kotlinx.serialization`, I need to apply JSON transformations to convert between different versions.

For example, a new field may be added which needs to hold the value of another field as the default value.

**Describe the solution you'd like**

I'm currently in the process of building an `ApiMigrationBuilder` operating on `JsonObject`. But, this seems like a common concern which may be of interest to others as well. Some example code of the builder I'm working on:

```
        override fun migrateRequest( request: JsonObject ): JsonObject = request.migrate {
            ifType( "com.example.ClassDiscriminator" ) {
                updateObject( "customer" ) {
                    copyField( "firstName", "userName" )
                }
            }
        }
```

Two questions:

1. Am I reinventing the wheel here? Does `kotlinx.serialization` or another library I am unaware about facilitate JSON manipulations like this on `JsonObject`?
2. Would there be an interest in contributing this to this library, or a separately published artifact?

**Comment by sandwwraith** [comment]
No, we do not provide any API to manipulate JsonObject except utilities already available in stdlib (given that JsonObject implements Map) Also see a question here: https://github.com/Kotlin/kotlinx.serialization/issues/1593

I'm not sure if it's possible to answer to your second question, because an 'API for manipulating JsonObjects' sounds very broad — both 'simple .edit extension' and 'full-fledged JsonPath API' fall under this definition. I think most people are happy with their custom extensions, but I may be wrong.

**Comment by shanshin** [comment]
Closed as answered
