### ISSUE TITLE
Support for `@Transient abstract val`

### ISSUE THREAD

**Issue by mgroth0** [Kotlin/kotlinx.serialization#2077]
My use case is that I have a class hierarchy where I want to never serialize a certain property:

```kotlin
@Serializable sealed class SuperClass(

) {
  abstract val transientProperty: Boolean
}

@Serializable class SubClass1: SuperClass() {
  override val transientProperty get() = false
  val serializedProperty1 = false
}

@Serializable class SubClass2: SuperClass() {
  override val transientProperty = false
  val serializedProperty2 = false
}

```

In the case above, I have forgotten to make `transientProperty` of `SubClass2` transient. I could change it to the `get() = ` syntax or add `@Transient`, but then I have to add that for every subclass which has less enforcement and denser code.

I would like to just do: 
```kotlin
@Transient abstract val transientProperty: Boolean
```

**Comment by sandwwraith** [comment]
I think it would be largely impossible for the same reason why `@SerialName` is non-inheritable (see discussion here: https://github.com/Kotlin/kotlinx.serialization/issues/2054#issuecomment-1274541701). Moreover, since we do not have a `@NonTransient` annotation, it would be impossible to reverse this behavior once the superclass is annotated — so, definitely, a new annotation is needed instead of changing the current one's behavior.
