### ISSUE TITLE
Un-actionable Gradle warning: There are multiple versions of "kotlin" used in nodejs build: 1.7.20, 1.7.21.

### ISSUE THREAD

**Issue by mgroth0** [Kotlin/kotlinx.serialization#2138]
**Describe the bug**

A gradle warning occurs, likely due to kotlinx.serialization:

`There are multiple versions of "kotlin" used in nodejs build: 1.7.20, 1.7.21. Only latest version will be used.`

I use kotlinx.serialization `1.4.1` as a dependency of our custom Gradle plugin. We then execute our main project, which uses this plugin, in an environment where all kotlin versions are `1.7.21`. 

I have not confirmed 100% that kotlinx.serialization is causing the warning. However, I'm pretty sure it is. kotlinx.serialization `1.4.1` uses kotlin 1.7.20, so it seems likely.

**To Reproduce**

It occurs in every single one of my gradle builds. Creating a reproducer might take a bit of time, but essentially:
1. Build a custom gradle plugin that depends on kotlinx.serialization 1.4.1
2. Use that custom gradle plugin in a project that is using kotlin 1.7.21

**Expected behavior**

For there to be no warnings

**Proposed solution**

Create a minor release where the kotlin version is bumped to 1.7.21

**Comment by sandwwraith** [comment]
I don't think it has to do anything with serialization, as we don't provide this warning. Serialization contains stdlib dependency because, well, it uses Kotlin stdlib. However, it does not depend on Kotlin compiler or Kotlin Gradle plugin (if we do not take the compiler plugin into account). Normally, Gradle dependency resolution will ignore that serialization depends on 1.7.20, if 1.7.21 is used explicitly — because the last version is taken by default. So if you're experiencing problems with custom plugins, look at the dependency resolution rules there.
