### ISSUE TITLE
Android Studio problem setting up kotlinx serialization

### ISSUE THREAD

**Issue by robmandoe** [Kotlin/kotlinx.serialization#218]
I followed the README.md

After adding all the lines to my project build.gradle, specifically... 
  compile "org.jetbrains.kotlinx:kotlinx-serialization-runtime:$serialization_version"

I get...
  Failed to resolve: org.jetbrains.kotlinx:kotlinx-serialization-runtime:0.6.1

I really want to use this extension. It typifies what Kotlin is all about. But you guys need more documentation on setting it up for Android Studio. A sample Android Studio build.gradle would be nice.

**Comment by sandwwraith** [comment]
`Failed to resolve` error usually means that you have not added kotlinx bintray repository to yours `build.gradle` file. Since this library is not published to jcenter yet, additional repository is needed, like this:

```gradle
repositories {
    jcenter()
    maven { url "https://kotlin.bintray.com/kotlinx" }
}
```
Probably you've mislooked it, since it is present in the example. Repository is needed in both `buildscript`'s and top-level `repositories` block.

I don't get your last note since there are no difference in buildfiles for Android Studio or IntelliJ IDEA. They are defined by Gradle syntax, not IDE.

**Comment by sandwwraith** [comment]
Outdated?

**Comment by friederikewild** [comment]
@sandwwraith Thanks. Worked combining the readme steps with this info: 
`Repository is needed in both buildscript's and top-level repositories block.`
Probably could be helpful to include this in the readme? It had sounded to me as if it's only needed inside the `buildscript's repositories` from the context.

**Comment by sandwwraith** [comment]
@friederikewild It is now required only at top-level, it is shown near to 'add dependency on the serialization runtime library' in the readme

**Comment by edWAR6** [comment]
Please fix the readme, is really confusing.
