### ISSUE TITLE
Is there any way to make `@MetaSerializable` accept a custom Serializer?

### ISSUE THREAD

**Issue by MikiLoz92** [Kotlin/kotlinx.serialization#2184]
Suppose I need to add Serializable behaviour to a custom annotation:
```kotlin
@MetaSerializable
annotation class MongodbResource(...)
```
An example: I have different kinds of MongoDB resources. Each of them will be annotated with a `@MongodbResource` annotation. However, I'd like to provide a separate `Serializer` (rather than the default one, generated by the presence of `@MetaSerializable`) to each of them, because say I have some custom persistence rules and store a few extra fields.

I can do that if I annotate each Resource with `@Serializable(with = ...)`, but the point is to be able to skip that annotation and have all different behaviors (both domain-specific and serialization-wise) incorporated in just one annotation, in this case my `@MongodbResource`.

The way I see this use-case being fulfilled is if `@MetaSerializable` had an optional property named something like a `serializerProperty` which would use to pick up the target annotation class' property that defines the Serializer:
```kotlin
@MetaSerializable(serializerProperty = "serializer")
annotation class MongodbResource(
    val serializer: KClass<*>,
    ...
)

```
Then I could annotate resources with `@MongodbResource(serializer = ...)` and all would be good. Although I'm not sure that this works at compile-time.

Please let me know if there's an already existing way of doing something like this, though.

**Comment by sandwwraith** [comment]
Initially, this idea was in a design draft (https://youtrack.jetbrains.com/issue/KTOR-2704/Serializable-Meta-Annotation), but it was omitted for simplicity and better readability — explicit `@Serializable(with)` is arguably better than implicit, when user doesn't know which exact serializer would be applied.

Also, 'one serializer fits all classes pattern' is usually discouraged for kotlinx.serialization, because `deserialize` often becomes type-unsafe, generic classes' serializers must have specific constructors, and so on.

**Comment by sandwwraith** [comment]
Linked: #1127
