### ISSUE TITLE
Unsupported start group or end group wire type: 7

### ISSUE THREAD

**Issue by Terrency** [Kotlin/kotlinx.serialization#2185]
It is Strange, when I use ProtoBuf.decodeFromByteArray to decode a ByteArray, it occoured
I found the reason, because of filter variable is nullable, after i delete "?", it can decode normal, why this happen, and this exception is confused.

**To Reproduce**
```
@Serializable
    data class Project(val name: String, val language: String)
@Test
    fun testProtobuf(){
        val filter: Project? = Project("kotlinx.serialization", "kotlin")
        val bytes = ProtoBuf.encodeToByteArray(filter)
        val obj = ProtoBuf.decodeFromByteArray<Project>(bytes)
        println(obj)
    }
```
can make it decode normal by replace with 
```
val filter: Project = Project("kotlinx.serialization", "kotlin")
```
kotlinx.serialization.protobuf.internal.ProtobufDecodingException: Unsupported start group or end group wire type: 7
	at kotlinx.serialization.protobuf.internal.ProtobufReader.skipElement(ProtobufReader.kt:64)
	at kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeElementIndex(ProtobufDecoding.kt:230)

**Comment by shanshin** [comment]
Hi,
due to the fact that protobuf does not support null values, in the case of using some nullable types, kotlinx Serialization uses an additional wrapper over these types.
Therefore, it is necessary to use nullable types very carefully.

In your code, the encoded type is different from the decoded one (`Project?` and `Project`), however, the types must match.

To decode correctly, you may change your code like this 
```
val obj = ProtoBuf.decodeFromByteArray<Project?>(bytes)
```

**Comment by shanshin** [comment]
Please feel free to create new issue if you have additional questions
