### ISSUE TITLE
Why is the stream APIs slower than the string APIs

### ISSUE THREAD

**Issue by Elvis10ten** [Kotlin/kotlinx.serialization#2186]
I switched from the stream api to the string API and noticed a more than 2x improvement in performance.

Is this expected? If so, I don’t see it documented.

This was ran on version 1.4.1 . I see there were some stream improvements in 1.5.0-RC. Does this bring the stream APIs on par with strings?

Thanks.

**Comment by sandwwraith** [comment]
I'd say this is a broad question. Answering it requires understanding what exactly did you see and what you mean by 'slower'. What was the stream source — file or network? Are you sure that this is not a problem with your InputStream performance? Was the payload large or small? How you measured the performance, by JMH benchmarks or by some other metrics, e.g. wall time? It would be helpful if you describe what exact testing you conducted and its results, or attach a sample benchmark.

Generally, string parser and stream parser share a large part of the codebase, so I can't say that 'one is significantly slower than another'. It is, however, possible if some specific unexpected conditions occur - that's why I'm asking the questions.

**Comment by shanshin** [comment]
@Elvis10ten 
if the tests are identical and fully-in-memory stream is used, then in 1.5.0 some slowdown is expected for the encoding operation: 30-100%, depending on the size of the strings, the presence of escape characters, the encoding used, etc.
The main reason is that when working with java.lang.String, the text is stored in an internal representation, operations with which the JVM itself can optimize.
But in the case of OutputStream, additional UTF-8 encoding operation must be performed, which increases the encoding time.

In version 1.5.0, additional optimizations were implemented, so the decoding speed of the streams should be comparable to the string.

**Comment by shanshin** [comment]
It is also worth considering that writing UTF-8 bytes to the stream takes some extra time, in this case the speed of operations does not depend on kotlinx.serialization.
Writing to a file or network socket can significantly slow down encoding/decoding, but even writing to memory takes some time.

**Comment by Elvis10ten** [comment]
The json file is about 96KB.

In the string test, I do: fileInputStream.bufferedReader().readText(). The time to read text is included in the measurement.

In the stream test, I do: fileInputStream.buffered() and I pass that to the stream API.

I just did simple profiling with Android’s SystemClock.ellaspedTime API.

——-

The min and max measurement are smaller with the string API than they are with the stream.

And also Gson has a similar performance to the string API.

Both of these has lead me to believe that the fault lines somewhere with the stream API.

**Comment by sandwwraith** [comment]
Thank you for the details. We'll try to reproduce measurements and identify the problem. As far as I understood, measurements were taken on an Android device? Or on an emulator?

**Comment by sandwwraith** [comment]
Also, can you please try 1.5.0-RC and check if you have the same results?

**Comment by Elvis10ten** [comment]
Android device.

it would be hard to try 1.5.0 as it forces us to upgrade the Kotlin version in the project.

**Comment by shanshin** [comment]
Hi,
@Elvis10ten, have you tried version 1.5.0 yet?

**Comment by shanshin** [comment]
Fill free to reopen issue if problem reproduced again
