### ISSUE TITLE
Integer discriminator for polymorphic types

### ISSUE THREAD

**Issue by silmeth** [Kotlin/kotlinx.serialization#2188]
Hi, I’m trying to [implement a binary format](https://gitlab.com/silmeth/pocztowka) (the one used by Rust’s [`postcard`](https://crates.io/crates/postcard) library) and I don’t know how to approach serialization of the polymorphic types.

The Rust library when given polymorphic data in the data-carrying enum format (similar idea to Kotlin’s sealed classes: the type has several variants with different data associated with each variant) by serializing the type-tag as an integer index (`0` for the first variant, `1` for the second, and so on).

`kotlinx.serialization` by default first serializes the `type` as a full module path of the specific type and it allows customization of it using the `@SerialName` annotation – but it requires the type name to be a string. Is there a nice solution to make the format use consecutive integers as variant discrimators in polymorphic data instead? How would one approach this?

The default behaviour works well in general, the format serializes and deserializes polymorphic data without issues, but I’d like it to get as close to the format produced by the Rust library as possible.

**Comment by pdvrieze** [comment]
@silmeth This is a hard one, there are many potential problems to using integer indices (their lack of stability for one). The library would need to be changed to support this as well. Perhaps a more convenient way would be to write a custom serializer for the polymorphic base type that implements the correct behaviour and then uses the appropriate child serializer. This custom serializer can do its own mapping from integers (or whatever) to the types.

**Comment by silmeth** [comment]
Yes, the lack of stability is a problem. I was wondering if maybe requiring some additional annotation on the variants (similar to `@SerialName`, maybe `@SerialId` or `@TypeId` with integer value?) would be a good solution. I guess I should read the implementation of `PolymorphicSerializer` and see what it does and it handles those, and if I’d be able to replace it for this single specific format.

**Comment by sandwwraith** [comment]
We don't support integers as polymorphic type tags for now, but we have a duplicate feature request: #2142

**Comment by sandwwraith** [comment]
@silmeth Type discriminators are common for all formats (as you said, they're defined by serial names), so it doesn't matter if it is a Json or not

**Comment by pdvrieze** [comment]
@silmeth It is perfectly valid for a format to use an integer as a type discriminator. It will need a format specific way to determine that discriminator/and type serial name from the number. This can be done using `SerialInfo`-ish annotations specific to the format, or some sort of generic mapping.

This is for example what the XML format does, it uses the tag name rather than the type's serialname (in the autopolymorphic mode). But it requires the format to do some extra work to produce the mapping in addition to handling polymorphic serializer to not let it perform its default serialization behaviour (it comes with its own serialkind so it is easy and supported to detect/special case).

Serializers however should be targeting the common case (perhaps special casing some formats), and the typename is a better default/common case than hardcoding numbers where some formats cannot deal with that.
