### ISSUE TITLE
Regression in 1.5.0: NullPointerException when initializing a polymorphic SerializersModule in a companion object 

### ISSUE THREAD

**Issue by OliverO2** [Kotlin/kotlinx.serialization#2236]
This code compiles and runs fine up to `kotlinx-serialization-json:1.5.0-RC`:

```kotlin
import kotlinx.serialization.Serializable
import kotlinx.serialization.modules.SerializersModule
import kotlinx.serialization.modules.polymorphic
import kotlinx.serialization.modules.subclass

@Serializable
sealed class Base {
    companion object {
        val serializersModule = SerializersModule {
            polymorphic(Any::class) { subclass(Derived::class) }
        }
    }
}

@Serializable
class Derived(var value: String) : Base()

fun main() {
    val derived = Derived("I am derived")
    println("derived: ${derived.value}")
}
```

With `kotlinx-serialization-json:1.5.0`, it produces a `NullPointerException` when invoking the inline `subclass` function:

``` 
> Task :run FAILED
2 actionable tasks: 2 executed
Exception in thread "main" java.lang.ExceptionInInitializerError
	at MainKt.main(Main.kt:19)
	at MainKt.main(Main.kt)
Caused by: java.lang.NullPointerException
	at Base.<clinit>(Main.kt:32)
	... 2 more
```

Plugins:
* `kotlin("multiplatform") version "1.8.10"`
* `kotlin("plugin.serialization") version "1.8.10"`

JVM dependency:
* `implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.0")`

**Comment by sandwwraith** [comment]
The problem related to the replacement of reflective lookup in `subclass(Derived::class)` with direct `subclass(Derived.serializer())` access (#1348). However, serialization plugin is not to blame here, but the Kotlin/JVM initialization order is. The same `ExceptionInInitializerError` can be reproduced without the plugin with a simple code:

```kotlin
sealed class Base {
    companion object {
        val serializersModule = Derived.foo()
    }
}

class Derived(var value: String) : Base() {
    companion object {
        fun foo(): String = "foo"
    }
}
```

It happens because:
1. Properties from `Base.Companion` are compiled to static fields in `Base` and are initialized in `Base.<clinit>`. 
2. Initialization of `Base` should happen before initialization of `Derived`, because it is a superclass. 

Therefore, during initialization of `Base`, `Derived.Companion` does not yet exist and causes NPE.

I doubt it can be meaningfully fixed in the compiler, so I can suggest using various workarounds: move property out of companion, use property with an explicit getter (i.e. without initializer) or use `by lazy {}` delegation.

**Comment by OliverO2** [comment]
Thanks for the analysis and excellent explanation. I was suspecting an initialization order problem, but could not find out, why this was surfacing due to a seemingly small library change only (using the 1.8.10 compiler plugin throughout). Could you point me to the commit which introduced the changed behavior?

From my point of view this problem can be closed now. Replacing the `val serializersModule` assignment with an extra `get()` is a viable option as these serializer modules are collected and combined into a complete module chain only once.

**Comment by sandwwraith** [comment]
@OliverO2 The commit that enables intrinsics is located in the [compiler]( https://github.com/JetBrains/kotlin/commit/a59f5f407bb90847ceec5c4acda241a47245a963) and is present in 1.8.0/1.8.10+. It also requires a runtime 1.5.0 though, because it relies on some runtime functions.

**Comment by sandwwraith** [comment]
I've filed https://youtrack.jetbrains.com/issue/KT-57374 for this case
