### ISSUE TITLE
Can't locate default serializer for class kotlin.Any

### ISSUE THREAD

**Issue by IvanSakharovskii** [Kotlin/kotlinx.serialization#240]
Hi! 
I'm trying to use kotlinx.serialization in library where I need to serialize data. In function needed to pass  param that should be serialized, but its type is unknown. So the main function is:
`fun toJson(src: Any): String = JSON.stringify(src)`
But this function returns `kotlinx.serialization.SerializationException` even if I pass class that has `@Serializable` annotation. 

Here's simple example: 
```
@Serializable
class MockDataString (
        private val message: String
) {
    fun getMessage(): String = message
}

@Test 
fun testKotlinSerialization() {
        val mockDataString = MockDataString("test")
        val serializable = JSON.stringify(mockDataString as Any)
        println(serializable)
}
```
I tried to use generics in function but have the problem with passing params to `JSON.stringify()` function.
`fun <T: Any> toJson(src: T): String = JSON.stringify(src)`
But it isn't even compile due to using T as reified type param.

**Comment by sandwwraith** [comment]
`JSON.stringify` itself is an inline function with reified type param, and because a statically known type is `Any`, framework can't obtain serializer to it. Workaround here is to extract serializer from real KClass before calling `.stringify` and pass it explicitly: 
```kotlin
fun foo(anyVal: Any): String {
    val serial: KSerializer<Any> = anyVal::class.serializer() // reflection call to get real KClass
    return JSON.stringify(serial, anyVal)
}```

The similar functionality is provided by the `serializerByValue` function in runtime lib (JVM only). Beware that described approach imposes a lot of limitations due to a reflection usage and type erasure: you won't be able to serialize in such way generic classes and standard collections, only classes w/o type arguments and marked as `@Serializable` are eligible.

**Comment by mochadwi** [comment]
> `JSON.stringify` itself is an inline function with reified type param, and because a statically known type is `Any`, framework can't obtain serializer to it. Workaround here is to extract serializer from real KClass before calling `.stringify` and pass it explicitly:
> 
> ```kotlin
> fun foo(anyVal: Any): String {
>     val serial: KSerializer<Any> = anyVal::class.serializer() // reflection call to get real KClass
>     return JSON.stringify(serial, anyVal)
> }
> ```
> 
> The similar functionality is provided by the `serializerByValue` function in runtime lib (JVM only). Beware that **described approach imposes a lot of limitations** due to a reflection usage and type erasure: you won't be able to serialize in such way generic classes and standard collections, only classes w/o type arguments and marked as `@Serializable` are eligible.

version 0.20.0 unable to use this anymore 

<img width="760" alt="Screen Shot 2020-07-09 at 2 45 32 PM" src="https://user-images.githubusercontent.com/7057959/87012094-00a13500-c1f3-11ea-94d6-d4d4423a29aa.png"> @sandwwraith
