### ISSUE TITLE
Protobuf Schema for RPC Services

### ISSUE THREAD

**Issue by Pseudow** [Kotlin/kotlinx.serialization#2476]
Protobuf Schema is a part of kotlinx serialization library which allows from kotlin classes generate proto messages.

**What is your use-case and why do you need this feature?**
The most common usage of protocol buffer is with **RPC protocol**. I am currently trying to make my main backend server using Kotlin/Spring. My **classes** and all my **services** are then generated into **proto files** if they get any changes so that my other applications can **update** with the generated proto files. Everything is working pretty fine, but I can't really find a way to serialize my services. I have thought of modifying the protobuf schema myself but the density of the project is scarying me.

**Describe the solution you'd like**
THe protobuf schema could serialiaze interfaces so that all functions parameters and returns value form a proto service.
```kotlin
@Serialize
interface GreetingService {
  fun sayHello(request: HelloReques): HelloReply
}
```
```proto
service Greeter {
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}
```
Thanks.

**Comment by sandwwraith** [comment]
Sorry, I don't quite get the question. What do you mean by `THe protobuf schema could serialiaze interfaces`? As far as I understood, you are talking about gRPC schemas for interfaces, not protobuf for data.
If you ask about generating Kotlin interfaces using existing gRPC schema, this is out of this project's scope. kotlinx.serialization does not and won't have RPC functionality. It can be implemented separately on top (but I don't know any existing projects yet). The same goes actually for generating gRPC schema from existing Kotlin interfaces. It is also not possible to alter the existing `ProtoBufSchemaGenerator` for that because kotlinx.serialization doesn't have any functionality to introspect interface methods.

**Comment by Pseudow** [comment]
Okay thank you for your answers!
