### ISSUE TITLE
Segmentation fault for Kotlin/Native target when decodeFromString

### ISSUE THREAD

**Issue by Tlaster** [Kotlin/kotlinx.serialization#2514]
**Describe the bug**
Segmentation fault for Kotlin/Native target when decodeFromString

**To Reproduce**
I've create a repo that can reproduce the error: https://github.com/Tlaster/kotlinx-serialization-test
just run `./gradlew check`, the JVM target can pass the test, but not the Kotlin/Native target

**Expected behavior**
I can use decodeFromString without any error.

**Environment**
 - Kotlin version: 1.9.20
 - Library version: 1.6.0
 - Kotlin platforms: JVM, macosArm64, macosX64, linuxX64, mingwX64, iosX64, iosArm64, iosSimulatorArm64
 - Gradle version: 8.2

**Comment by sandwwraith** [comment]
Thanks, reproduced. Can you please point to the sources of `"moe.tlaster:bluesky:0.0.1-SNAPSHOT"`? I'd like to try to check if there is a problem with the model.

**Comment by Tlaster** [comment]
> Thanks, reproduced. Can you please point to the sources of `"moe.tlaster:bluesky:0.0.1-SNAPSHOT"`? I'd like to try to check if there is a problem with the model.

It's here: https://github.com/Tlaster/ozone

**Comment by sandwwraith** [comment]
After poking here and there, I can conclude that this is some kind of very complex initialization cycle that leads to accessing not-yet-created object (which may have been NPE on JVM, but given it is native, it is a segfault).

So, If I try to break down the hierarchy, it looks like this:

```
RecordView.serializer() ->
	RecordViewRecordUnion.serializer().init() // 1 ->
	   RecordViewRecordUnion.ViewRecord.serializer() -> ViewRecordSerializer ->
	   	   RecordViewRecord.serializer() ->
	   	       RecordViewRecordEmbedUnion.serializer() ->
	   	          SealedValueClassSerialNameKSerializer.init() -> // triggers computation of RecordViewRecordEmbedUnion.RecordView.serializer().hashCode(), 
	   	            RecordViewRecordEmbedUnion.RecordView.serializer() ->
	   	                 RecordView.serializer() // to compute hashCode, we need to know RecordViewRecordUnion.serializer().hashCode, but it is not created yet because we are still in (1)
```

The problem is that while creating RecordViewRecordUnion.serialzier(), you need to create all sealed subclasses' serializers,  and down below, in `RecordViewRecordEmbedUnion.RecordViewSerializer `, it tries to reference  `RecordView.serializer()`, which contains reference to `RecordViewRecord` which we are creating right now. It is not a problem per se, but ` SealedValueClassSerialNameKSerializer.init()` tries to compute hashCode for RecordView.serializer().descriptor, and to know that, we need to know   `RecordViewRecordUnion.serialzier().descriptor.hashCode()` — and it is still not available.

I'm not entirely sure why JVM is not failing with the same error; likely, initialization order on the JVM slightly differs from Native (or perhaps it first stores the variable, but does not initialize it correctly, which may lead to even more subtle bugs).         

In any way, I'd recommend to try to break this cycle. As a simple workaround, add `by lazy{}` to `SealedValueClassSerialNameKSerializer.descriptorMapping` initializer.

**Comment by Tlaster** [comment]
Thanks! Break the cycle works for me!
