### ISSUE TITLE
Serializable to any type.

### ISSUE THREAD

**Issue by Daeng96** [Kotlin/kotlinx.serialization#2551]
I have a json response whose property/variable evaluates to false (Boolean) when the value is null.

```
data class MyClass (
      val id: Any // false when id not found. 
)

```

**I want it like this:**

```
@#Serializable
data class MyClass (
      val id: Int?
)
```

**Comment by pdvrieze** [comment]
What do you mean? Do you want the serialized value to be "false" instead of absent/null? Is the json response external? In any case what you want to do in this case is to use a custom serializer. This could either be on `MyClass` or on id/`Int` (a special nullable serializer that substitutes false for null ...)

**Comment by Daeng96** [comment]
> What do you mean? Do you want the serialized value to be "false" instead of absent/null? Is the json response external? In any case what you want to do in this case is to use a custom serializer. This could either be on `MyClass` or on id/`Int` (a special nullable serializer that substitutes false for null ...)



**I have a case like this >
**

[Stackoverflow](https://stackoverflow.com/questions/76902212/how-to-deserialize-a-json-response-where-null-keyword-is-replaced-with-false)

**Comment by pdvrieze** [comment]
Yes, you'll probably want a custom serializer (with a descriptor that is nullable). The custom serializer should special case Json, and for encoding is straightforward (encode false on null, encode the original value otherwise). For decoding you need to read the raw value and determine whether it is a false, or another value. You can then use a typealias to attach the serializer to the primitive.
There might be some approaches for code reuse as well (mimicking NullableSerializer), although it is something ideally addressed in the format.
