### ISSUE TITLE
Throwing an exception from getElementDescriptor is problematic

### ISSUE THREAD

**Issue by pdvrieze** [Kotlin/kotlinx.serialization#258]
The current implementation of the default serialDescriptor throws an exception when the descriptor is not actually available. In the case where introspecting children, some of those children are primitives. In that case returning null may be valid, but throwing is an overhead.

Generated serializers do not yet work correctly either, not having child serializers registered.

**Comment by sandwwraith** [comment]
Although library contains API for it in the current release, it is not working yet because corresponding changes in the plugin are not yet finished and therefore not merged in the upstream compiler, so for now `.getElementDescriptor` is basically a stub which throws an exception unless you've implemented the descriptor manually. 

In the usual use-cases, the descriptors almost always would be there, so I doubt it is reasonable to make the return type nullable. Primitive kinds indeed do not have them and throw an error, but it is reflected in `getElementsCount` which will return 0. Moreover, typical suggested approach to traverse descriptors is to make `when(descriptor.kind)` and you simply can skip asking descriptors in `is PrimitiveKind` branch. Do you have any examples where this approach would be inefficient?

**Comment by pdvrieze** [comment]
What I meant here is that I have a type that has primitive children: `@Serializable data class A(val x:Int, val y:Int)`. The descriptor for A could return either `null` for the `x` child or better a suitable descriptor. From what you say the latter is the intended design which is better as it gives access to the kind, but if it were to return null this could be sufficient in some cases. The inefficiency would be to use `A.serializer().descriptor().getElementDescriptor(0)` and get an exception (which cannot be avoided/checked).

Btw. is there some idea what kind of descriptor to return for unknown values (that get serialized through the unknown/unserializable value mechanism)? Of course if values without serializer are supported at all.

**Comment by sandwwraith** [comment]
Yes, `A.serializer().descriptor.getElementDescriptor(0)` should return `IntDescriptor` normally. It throws exception currently because this feature is not implemented yet, which is emphasized in the changelog. `IntDescriptor`, indeed, will throw an exception on attempt to get its element descriptors, but it has elementsCount=0 so it is kinda inevitable. Maybe extension `getElementDescriptorOrNull` which checks count and primitive kinds will be added later — as an analogy to lists which have `get(index)` and `getOrNull(index)` with additional range check.

Only ContextSerializer is allowed for unknown values, other values will trigger compile error. I think it would have its own descriptor eventually (or some delegating at runtime descriptor).

**Comment by pdvrieze** [comment]
I missed it in the changelog although I found it quickly enough. I'm still using my canary to get my own data ;-)
