### ISSUE TITLE
JS, JSON: Negative zero float/double not preserved during serialization

### ISSUE THREAD

**Issue by damianw** [Kotlin/kotlinx.serialization#2599]
Given this test:

```Kotlin
class NegativeZeroTest {

    @Test
    fun serializeDouble() {
        assertEquals("-0.0", Json.encodeToString<Double>(-0.0))
    }

    @Test
    fun serializeFloat() {
        assertEquals("-0.0", Json.encodeToString<Float>(-0.0f))
    }

    @Test
    fun deserializeDouble() {
        assertEquals((-0.0).toBits(), Json.decodeFromString<Double>("-0.0").toBits())
    }

    @Test
    fun deserializeFloat() {
        assertEquals((-0.0f).toBits(), Json.decodeFromString<Float>("-0.0").toBits())
    }
}
```

The first two tests, `serializeDouble` and `serializeFloat`, pass on Kotlin/JVM but not on Kotlin/JS. Both of these serialize to the literal `0`, losing the [negative information](https://en.wikipedia.org/wiki/Signed_zero).

**Expected behavior**
The negative zero should be preserved in Kotlin/JS the same as it is on Kotlin/JVM.

**Workaround**

One can implement a serializer like this to work around the problem:

```kotlin
@OptIn(ExperimentalSerializationApi::class)
class DoubleSerializer : KSerializer<Double> {

    override val descriptor: SerialDescriptor
        get() = Double.serializer().descriptor

    override fun serialize(encoder: Encoder, value: Double) {
        if (value == 0.0) {
            (encoder as JsonEncoder).encodeJsonElement(JsonUnquotedLiteral(if (value.toBits() == 0L) "0.0" else "-0.0"))
        } else {
            encoder.encodeDouble(value)
        }
    }

    override fun deserialize(decoder: Decoder): Double = decoder.decodeDouble()
}
```

**Environment**
 - Kotlin version: `1.9.22`
 - Library version: `1.6.3`
 - Kotlin platforms: JS

**Comment by sandwwraith** [comment]
Unfortunately, this is how `Double.toString()` works on JS — because native JS `Number` does so. Both `println((-0.0).toString())` and `println(0.0.toString())` still give `0` in the output. We examined the possibility of handling this inside the serialization framework but concluded that the performance hit of handling `-0.0` manually is not worth it. It is something that better be fixed in Kotlin itself (for reference: https://youtrack.jetbrains.com/issue/KT-33358).  Note that by definition, `-0.0 == 0.0`, so for most practical applications it doesn't really matter.

**Comment by pdvrieze** [comment]
> ```kotlin
> class DoubleSerializer : KSerializer<Double> {
> ```

**Note** that you can use the a slightly rewritten/tidied up serializer for each case you need the precision/distinction (this is used by using `NegativeZeroDouble` instead of `Double` for your fields (it is still actually a double):
```kotlin
typealias NegativeZeroDouble=@Serializable(NegativeZeroDoubleSerializer::class) Double

class NegativeZeroDoubleSerializer: KSerializer<Double> {

    override val descriptor =
        PrimitiveSerialDescriptor("org.example.NegativeZeroDoubleSerializer", PrimitiveKind.DOUBLE)

    override fun serialize(encoder: Encoder, value: Double) {
        if (value == 0.0 && encoder is JsonEncoder) {
            encoder.encodeJsonElement(JsonUnquotedLiteral(if (value.toBits() == 0L) "0.0" else "-0.0"))
        } else {
            encoder.encodeDouble(value)
        }
    }

    override fun deserialize(decoder: Decoder): Double = decoder.decodeDouble()

}
```
Basically there were two issues:
- You need a different serial name as serial names are supposed to be unique (and are used for caching by some formats)
- You want to fallback to a default implementation if the encoder isn't Json, rather than implement it such that the serialization only works with one format (Json)
