### ISSUE TITLE
Whether to support enum specifying fields for serialization instead of enum names?

### ISSUE THREAD

**Issue by qnxy-ck** [Kotlin/kotlinx.serialization#2613]
Whether to support enum specifying fields for serialization instead of enum names
![image](https://github.com/Kotlin/kotlinx.serialization/assets/38235312/fb6be952-0380-494b-a9a3-539c0cc0ba65)

Although it can be customized, it would be great if it could be supported by default

![image](https://github.com/Kotlin/kotlinx.serialization/assets/38235312/8ed14238-264c-452b-9af0-e642695c4825)

For example, add a @SerialVal annotation

![image](https://github.com/Kotlin/kotlinx.serialization/assets/38235312/ace4e213-59de-48ec-91e7-ec4252c8aa6c)

**Comment by xiaozhikang0916** [comment]
You might indicating [Enum ordinal](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-enum/ordinal.html) here because custom fields in enum cannot stand for a concreate enum instance identically.

IMO, ordinal has less version compatibility than enum names. Developers can change the order of enum definitions without any break changes, but renaming does not.

**Comment by sandwwraith** [comment]
See a similar discussion here: https://github.com/Kotlin/kotlinx.serialization/issues/2563#issuecomment-1927806203
@xiaozhikang0916 made a valid point — you cannot check at compile time that `typeNum` will contain unique values. Also we would additionally need to check whether this type is compatible (String or Int or ...), and all various things.
In short, the idea 'Serialize a class as some specific value I have chosen' is a definition for a custom serializer, and a custom serializer is a recommended way to do it. In case you have multiple enums, you can use a hint from linked comment (to define abstract base serializer).
