### ISSUE TITLE
Serializer disrupts data class copy method

### ISSUE THREAD

**Issue by linean** [Kotlin/kotlinx.serialization#2614]
**Describe the bug**
Recently, I encountered code where JSON was deserialized into a data class field that wasn't declared within the constructor. Given that there's no reflection involved, I became curious about the mechanism behind it and observed that the compiler generates an additional constructor.

The problem arises when this new constructor isn't factored in during data class copying, resulting in rather challenging debugging scenarios.

**To Reproduce**
Run the following test
```
class ExampleTest {

    @Serializable
    data class TestClass(val input: String) {

        val param: String = input
    }

    @Test
    fun `param should be equal`() {
        val json = """{"input":"a","param":"b"}"""
        val testClass = Json.Default.decodeFromString<TestClass>(json)
        val classCopy = testClass.copy()

        assertEquals(
            testClass.param, classCopy.param,
        )
    }
}

```

**Expected behavior**
I believe it would be beneficial to implement a flag enabling deserialization exclusively into fields specified within the data class constructor. While marking param as transient resolves the issue, there's a concern that it could be overlooked.

**Environment**
 - Kotlin version: 1.9.22
 - Library version: 1.6.0
 - Kotlin platforms: JVM
 - Gradle version: 8.1.1

**Comment by pdvrieze** [comment]
That is some curious behaviour indeed. One consideration is that the plugin doesn't treat data classes specially. For the general (non-data) case it would be necessary to verify the construction if the data is untrusted. This appears the case for data classes too.

**Comment by sandwwraith** [comment]
Indeed, the serialization plugin does not differentiate data and non-data classes. To be honest, body properties of data classes may bring a lot of unobvious problems by themselves: they are absent from equals and hashcode, they're not mentioned in to string, and this behavior is a result of them not being used in the `copy`. So to me, it is a design limitation of data classes, rather than a serialization plugin problem. Same issue is likely bound to happen with any framework that bypasses the primary constructor (e.g. sets `param` with reflection). Since we cannot provide a diagnostic or a flag for every case, this is something that one have to remember about.

For reference (not related, but mentions other `copy()` problems): https://youtrack.jetbrains.com/issue/KT-66628/Propagate-select-characteristics-of-data-classes-user-defined-member-declarations-to-corresponding-synthetic-member-declarations
