### ISSUE TITLE
Provide a best practice for formats that requiring a specified key order.

### ISSUE THREAD

**Issue by iseki0** [Kotlin/kotlinx.serialization#2646]
**What is your use-case and why do you need this feature?**
I'm trying to implement an encoder/decoder for the [Bencoding](https://www.bittorrent.org/beps/bep_0003.html#bencoding) format.
This format requires that keys in the dictionary type [appear in sorted order](https://www.bittorrent.org/beps/bep_0003.html#bencoding:~:text=appear%20in%20sorted%20order).
Currently, the structure encoding process is completely controlled by the serializer, which does not have a method to determine the best encoding order.

**Describe the solution you'd like**
Provide a way for the serializer to know the best order for encoding.

**Comment by pdvrieze** [comment]
@iseki0 Changing the way serializers work is a very complex undertaking that would require a lot of time at least for compatibility.

In the meantime the way to solve it is to "memoize" the serialization requests. Have the `CompositeEncoder` contain an array of serialization functions that you set when serialization of each member is requested. Then in the `endStructure` you actually perform the member serializations in the desired order. (Xml has a similar issue due to attributes and elements needing to be handled, and now actually having a feature allow almost arbitrary reordering)

**Comment by iseki0** [comment]
> @iseki0 Changing the way serializers work is a very complex undertaking that would require a lot of time at least for compatibility.
> 
> In the meantime the way to solve it is to "memoize" the serialization requests. Have the `CompositeEncoder` contain an array of serialization functions that you set when serialization of each member is requested. Then in the `endStructure` you actually perform the member serializations in the desired order. (Xml has a similar issue due to attributes and elements needing to be handled, and now actually having a feature allow almost arbitrary reordering)

Well. Maybe it's the easiest way for a workaround, since many bencoding data is not so large.
