### ISSUE TITLE
Crash at encode nest map

### ISSUE THREAD

**Issue by qq864064013** [Kotlin/kotlinx.serialization#2695]
Crash at encodeToString when encode a map with map element, example code:
```
        val map = mutableMapOf("cocosPluginSwitch" to "aa", "autoStartCocosConfig" to mapOf("abc" to 1))
        val mapstr = Json.encodeToString(map)
```

This is normal:
```
        val map = mutableMapOf("cocosPluginSwitch" to "aa", "autoStartCocosConfig" to "bb")
        val mapstr = Json.encodeToString(map)
```

**Comment by pdvrieze** [comment]
@qq864064013 If you just want to use the library to encode directly provided Json you should use the `JsonElement` type and its children.

EncodeToString uses statically typed values that are serializable. You likely got an error because the static type is `Map<String,Any>`. Map serializers are built in so you didn't get a compiler error, but without a serializersModule that maps polymorphic children it will not serialize (if it were to serialize it would do so differently than you expects).

**Comment by sandwwraith** [comment]
See thread and solution here: https://github.com/Kotlin/kotlinx.serialization/issues/746#issuecomment-791807112

In general, it is recommended to work with `JsonElement`/`buildJsonObject` builders rather than untyped `Map`s.
