### ISSUE TITLE
Why is Kotlinx Serialization 1.7 not 2.0 if it's a breaking change?

### ISSUE THREAD

**Issue by TWiStErRob** [Kotlin/kotlinx.serialization#2709]
**What is your use-case and why do you need this feature?**

See release notes: https://github.com/Kotlin/kotlinx.serialization/releases/tag/v1.7.0-RC

**Describe the solution you'd like**

2.0.0

**Comment by pdvrieze** [comment]
I would say this is because the change to interface polymorphic serialization is more a bug fix than anything else. It is only triggered if the interface is does not have a `Serializable` annotation. The old behaviour works as if there is no contextual serializer registered (any registration is ignored), where the new behaviour doesn't ignore it. The only way it breaks is if you had a contextual serializer registered even though it was never resolved.

**Comment by sandwwraith** [comment]
While we discussed this issue internally, we concluded that impact from the change is very narrow. It is indeed 'more of a bug fix' in a sense that if you wanted to have contextual interface serializer, it never worked in the first place, always returning a polymorphic one. Still, since this is a behavior change, we had to write a cautious note about it. The rest of the library remains the same, and it is compatible with previously compiled code. So 2.0 version bump is not justifiable, given that there are no other significant changes. Hope this answers your question.

**Comment by TWiStErRob** [comment]
And what do you think about the fact that a minor library update makes a requirement on a major new version? None of the projects compile which are still using Kotlin 1.9.22, of which there are plenty. Yes, we can **theoretically** swap in 1.6 with 1.7 at runtime, but **practically** we can't compile against 1.7.

---

Sidenote: why stick on 1.9? Simple: no tooling for 2.0. IDEs are not ready for it. Refactorings are missing, `.kts` files cannot be opened, etc. Android Studio specifically is outdated and cannot even **try** to use K2.

**Comment by pdvrieze** [comment]
> Sidenote: why stick on 1.9? Simple: no tooling for 2.0. IDEs are not ready for it. Refactorings are missing, `.kts` files cannot be opened, etc. Android Studio specifically is outdated and cannot even **try** to use K2.

The K2 support in Android Studio/Intellij is for the editor frontend, not for how your code is compiled. As 1.9 and 2.0 don't have syntax changes you can use all the nice support from the old IDE plugin support while still getting the (really much faster) compilation from k2.

**Comment by TWiStErRob** [comment]
Hmm, interesting. That makes sense of course. I wonder why I had such a bad first impression. I'll try updating a few projects and see if I find anything interesting.

Re projects that have some tech debt and cannot update to 2.0, our only option is sticking with serialization 1.6, right?
