### ISSUE TITLE
build.gradle.kts Gradle Kotlin DSL example

### ISSUE THREAD

**Issue by jrhy** [Kotlin/kotlinx.serialization#273]
Could you please provide a Gradle example using the Kotlin DSL?  I am trying this:

```
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import org.jetbrains.kotlin.gradle.dsl.Coroutines

buildscript {
	val kotlin_version = "1.3.10"
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath(kotlin("gradle-plugin", kotlin_version))
		classpath("org.jetbrains.kotlin:kotlin-serialization:$kotlin_version")
	}
}

plugins {
    kotlin("jvm") version "1.3.10"
    "kotlinx-serialization"
}

dependencies {
    compile(kotlin("stdlib-jdk8"))
    compile(kotlin("reflect"))
    testCompile(kotlin("test"))
    testCompile(kotlin("test-junit"))

    compile("com.fasterxml.jackson.module:jackson-module-kotlin:2.9.5")
    testCompile("io.kotlintest:kotlintest-runner-junit5:3.1.7")
    compile("redis.clients:jedis:2.9.0")
    compile("org.jetbrains.kotlinx:kotlinx-serialization-runtime:0.9.0")
}

tasks.withType<KotlinCompile> {
    kotlinOptions {
        jvmTarget = "1.8"
        freeCompilerArgs = listOf("-Xjsr305=strict")
    }
}

repositories {
    mavenCentral()
    maven (url="https://kotlin.bintray.com/kotlinx" )
}
```

But when I try to compile the example like `JSON.stringify(Data.serializer(), Data(42))`, I get the error:

```
e: src/main/kotlin/HelloWorld.kt: (260, 45): Unresolved reference: serializer
> Task :compileKotlin FAILED

FAILURE: Build failed with an exception.
```

**Comment by sandwwraith** [comment]
I suppose that plugin was not applied because you need something like `id("kotlinx-serialization") version ("1.3.0")` instead of just `"kotlinx-serialization"` line which does nothing. Consult Kotlin Gradle DSL documentation for a precise syntax of applying plugin.

**Comment by reitzig** [comment]
I have a working multi-platform example over at [reitzig/kovalscj](https://github.com/reitzig/kovalscj). I imagine that a subset of that Gradle file will work for single-platform projects?

**Comment by sandwwraith** [comment]
@reitzig I think this is a correct assumption

**Comment by herveDarritchon** [comment]
Hi,

I am also interested to have an example because it is not working straight away :(

When I try to setup kotlinx.serialization using gradle with kotlin dsl I have a gradle error : 

```
Plugin [id: 'org.jetbrains.kotlin.kotlinx-serialization', version: '1.3.11'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.jetbrains.kotlin.kotlinx-serialization:org.jetbrains.kotlin.kotlinx-serialization.gradle.plugin:1.3.11')
  Searched in the following repositories:
    Gradle Central Plugin Repository

```

This is my configuration : 

```
buildscript {

    val kotlinVersion: String by extra { "1.3.11" }

    repositories {
        jcenter()
    }

    dependencies {
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion")
        classpath("org.jetbrains.kotlin:kotlin-serialization:$kotlinVersion")
    }
}

plugins {
    application
    kotlin("jvm") version "1.3.11"
    kotlin("kotlinx-serialization") version "1.3.11"
}

repositories {
    jcenter()
    maven { setUrl("https://kotlin.bintray.com/kotlinx") }
}

dependencies {
    val ktorVersion = "1.1.1"

    fun ktor(module: String) = "io.ktor:ktor-$module:$ktorVersion"
    fun ktor() = "io.ktor:ktor:$ktorVersion"

    compile(kotlin("stdlib-jdk8"))
    compile(ktor())
    compile(ktor("server-netty"))
    compile(ktor("server-core"))
    compile(ktor("jackson"))
    compile(ktor("locations"))
    compile(ktor("metrics"))
    compile("org.jetbrains.kotlinx:kotlinx-serialization-runtime:0.9.1")

}
```

I tries several ways to solve this issue like using 
[When you can’t use the plugins {} block](https://docs.gradle.org/current/userguide/kotlin_dsl.html#sec:plugins_resolution_strategy)

But I have no way to fix it.

I find something weird, if I look at the repository : https://kotlin.bintray.com/kotlinx

In the directory https://kotlin.bintray.com/kotlinx/org/jetbrains/kotlinx/, there is no kotlinx-serialization subdirectory ?

So if someone can help, it would be great ! :)

Thanks.

**Comment by sandwwraith** [comment]
@herveDarritchon Have you added `pluginManagement` block to `settings.gradle` as [here](https://github.com/Kotlin/kotlinx.serialization#gradle-with-plugins-block)?

Sample from conversation above: https://github.com/reitzig/kovalscj/blob/master/settings.gradle#L1

**Comment by sandwwraith** [comment]
Btw, https://github.com/Kotlin/kotlinx.serialization#gradle-with-plugins-block actually is Gradle Kotlin DSL example so I suppose this can be closed.

**Comment by chadmorrow** [comment]
Here's how I got it working:

```
// settings.gradle.kts

pluginManagement {
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "kotlinx-serialization") {
                useModule("org.jetbrains.kotlin:kotlin-serialization:${requested.version}")
            }
        }
    }

    repositories {
        gradlePluginPortal()
        maven("https://kotlin.bintray.com/kotlinx")
    }
}

rootProject.name = "projectName"
```

and then in the build.gradle.kts file I included it like this:
```
// build.gradle.kts

plugins {
    kotlin("jvm") version "1.3.40"
    id("kotlinx-serialization") version "1.3.40"
}

dependencies {
    ...
    implementation ("org.jetbrains.kotlinx:kotlinx-serialization-runtime:0.11.1")
    ...
}
```

**Comment by mrfishy** [comment]
@chadmorrow The additions to the settings.gradle.kts file really broke thing loose for me. Thank you.  I did, however, have to add `jcenter()` to the repositories section to get it to work.   The repositories block now looks like:

```
	repositories {
		gradlePluginPortal()
		jcenter()
		maven("https://kotlin.bintray.com/kotlinx")
	}

```

**Comment by tomeeeS** [comment]
I tried the above and for me maven(..) in pluginManagement::repositories threw error. I have my repositories block in the module build.gradle and is now working fine. 
On Android this works right now:

`// settings.gradle
pluginManagement {
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "kotlinx-serialization") {
                useModule("org.jetbrains.kotlin:kotlin-serialization:${requested.version}")
            }
        }
    }
}
<your additional settings>`
`// module build.gradle
plugins {
    id("com.android.application")
    id("kotlin-android")
    id("kotlinx-serialization") version "1.3.11"
}

repositories {
    mavenCentral()
    google()
    gradlePluginPortal()

    maven { url "https://kotlin.bintray.com/kotlinx" }
    //etc
}

//....

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlinVersion"
    implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime:0.11.1"
    //....
}
`

**Comment by lukaszkalnik** [comment]
> Btw, https://github.com/Kotlin/kotlinx.serialization#gradle-with-plugins-block actually is Gradle Kotlin DSL example so I suppose this can be closed.

This is not Gradle Kotlin DSL - this example is in Groovy, only using the `plugins` block...

**Comment by toni-megalopter-com** [comment]
Please, can someone attach project sample with working kotlinx.serialzation.. I'm trying 4 days to setup kotlinx.serialzation and without success..

**Comment by sandwwraith** [comment]
@toni-megalopter-com see https://github.com/Kotlin/kotlinx.serialization/blob/master/examples/example-visitors/build.gradle.kts

**Comment by toni-megalopter-com** [comment]
tnx.

**Comment by toni-megalopter-com** [comment]
Hi Leonid,
obviously I'm missing something very basic, 
because many years of using M$ visual studio spoiled me ;-)..   ..  Added a   script and put that content in, from File> New..I intentionally changed to id ("xkotlinx-serialization") (I have the same outcome with "kotlinx-serialization" as well) .. still, get BUILD SUCCESSFUL in 26s, and, still, import kotlinx.serialization. * is not recognized [attached(url)](http://www.megalopter.com/nativeser.jpg)..and how I can add gradlew.bat into kotlin project? I searched all over the web but, could not find..?  I just want to build a simple hello world shared library with kotlinx.serialization..I already succeed to call shared .dll  from C Sharp but, I need to serialize objects so that I can transfer them to C#.Thanks!

**Comment by toni-megalopter-com** [comment]
Hi Leonid,
figured out  how to add gradlew.bat  by running the command 
gradle wrapper, but still no progress.. if I try to add .kts script that you sent me to trough IntelliJ>File>New Kotlin Script
and if I put the name:
build.gradle.kts
IntelliJ put it in folder build.

Can you help me, please? What I have to do in order to force your .kts works?

**Comment by toni-megalopter-com** [comment]
...build.gradle.kts
IntelliJ put it in folder build......And Intellij ignores it..

**Comment by toni-megalopter-com** [comment]
I'm trying to make this work in  IntelliJ..Should I use Clion?

**Comment by toni-megalopter-com** [comment]
Hi Leonid, I'm trying to change your project :
sandwwraith/KotlinSerializationPlayground
to get a .dll that I can call from C#, but unsuccessfully...
Usually, it works with 

kotlin {
  mingwX64("native") {
    binaries {
      sharedLib {
        baseName = "libnative"
      }
}

but only  with Kotlin 1.3.21
not with kotlin 1.3.70.

I see that native and serialization works on those two projects,
sandwwraith/KotlinSerializationPlayground
kotlinx.serialization

but, I need to call .dll from c# so I need serialization in kotlin native
in order to communicate between kotlin and c#

Can you point me in the right direction,please?

**Comment by toni-megalopter-com** [comment]
I can't figure out what I need to change and which combination of gradle ,kotlin ,java and plugins versions I have to use in order to get native .dll library that I can call from c# .. KotlinSerializationPlayground works only with java 1.8 and to get shared lib works only with kotlin 1.3.21.. it-s very painful to guess what combination of version works..

**Comment by toni-megalopter-com** [comment]
And all those examples are with serialization version 0.09 and the last one is 0.20..

**Comment by toni-megalopter-com** [comment]
Or should I simply wait for kotlin 1.4?
