### ISSUE TITLE
Errors revealed only on run-time

### ISSUE THREAD

**Issue by DorBSoft** [Kotlin/kotlinx.serialization#2739]
As mentioned in the documentation, for everything to work the compilation plugin should be added, and so do rules for proguard.
The issue is when using
 `fun <reified T> StringFormat.encodeToString(value: T): String ` and <br> `fun <reified T> StringFormat.decodeFromString(string: String): T`.<br> Missing to do all the proper configuration will not be seen on compile time but on run time.
This can happen when compilation setting change over time, or even just using a module which uses the library. Or by not testing all scenarios on release version. So we easily might not know it happened.
Luckily, using
`fun <T> encodeToString(serializer: SerializationStrategy<T>, value: T): String` and
 `fun <T> decodeFromString(deserializer: DeserializationStrategy<T>, string: String)` solve it all together. Errors will be on compile time and no need for proguard rules.

Enabling usage with minimal interface is important, but IMHO it is not as nearly as important as preferring compilation errors over run time errors.
I suggest deprecating the function that does not explicitly take a serializer. I suggest that meanwhile the documentation will detail the cons of using it.

**Comment by sandwwraith** [comment]
We explored this design at the early stages of the library (pre-1.0). It was not very convenient for a lot of reasons:

1. With generics, it quickly becomes too verbose — `encodeToString<List<MyBox<String>>>(value)` is much shorter than `encodeToString(ListSerializer(MyBox.serializer(String.serializer())), value)`. In most cases, type arguments can also be inferred by the compiler, which helps even more.
2. Frameworks (e.g., Ktor or Retrofit) typically operate serialization via `KType` and not with `KSerializer` directly (since KType allows you to use any serialization framework you'd like). Since `serializer(KType)` is a runtime operation that gives runtime errors, there is little profit from requiring the user to specialize the serializer explicitly — runtime errors from frameworks won't go away.
3. `@Contextual` and `SerializersModule` also postpone serializer resolving to runtime. If you want to use contextual serializer explicitly, you'd have to write something like `json.encodeToString(json.serializersModule.getContextual(MyValue::class), myValue))`. Which is repetitive — `json` was mentioned twice — and also does not provide compile-time safety.

So ultimately, `reified` type parameters in conjunction with `typeOf` and `serializer()` intrinsics are more convenient way than always-explicit serializer.

You can also check #2522 for a similar discussion.
