### ISSUE TITLE
Compile as .aar library: java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/serialization/json/JsonKt;

### ISSUE THREAD

**Issue by mistralaix** [Kotlin/kotlinx.serialization#2816]
**Describe the bug**
I have an android project. I have a submodule lib that implements the library kotlinx serialization and abstract the logic to send and serialize classes.

The goal is to compile the lib submodule as a library in **.aar** format.

On my android app, I want to import and use this **.aar** library (the app should not implement kotlinx serialization directly). Everything compiles but when I launch my app, I get this error from my lib code:

*java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/serialization/json/JsonKt;*

My app build.gradle.kts:

```kts
api(files("libs/lib-release.aar"))
```

My lib build.gradle.kts:

```kts
api("org.jetbrains.kotlinx.kotlinx-serialization-json:1.7.1")
```

**Environment**
 - Kotlin version: 2.0.10
 - Library version: 1.7.1
 - Kotlin platforms: Android
 - Gradle version: 8.5.2

Thank you for your help!

**Comment by msfjarvis** [comment]
What you're trying doesn't work, a compiled AAR has no dependency information so the `api` dependency is not doing anything useful. If you want to stick with this setup, you will need to add all the dependencies from your lib module to your app module manually.

This is not a kotlinx.serialization bug.

**Comment by EdricChan03** [comment]
I'm pretty sure an aar file doesn't contain its dependencies (by default) - they're resolved by a dependency management tool like Gradle or Maven. You'll have to create an "uber" aar of sorts, see https://stackoverflow.com/questions/34445399/create-an-aar-with-multiple-aars-jars, https://stackoverflow.com/questions/40405465/android-studio-create-aar-using-another-aar-file-and-jar-inside, etc

Out of curiosity, why are you directly using the aar file rather than publishing your library to a Maven repository (remote or local), and letting Gradle/Maven handle the transitive dependencies for you?

**Comment by sandwwraith** [comment]
The answers above are correct, I imagine additional setup is needed to pull kotlinx-serialization as a transitive dependency.

**Comment by mistralaix** [comment]
Thank you everyone for your input! Letting maven to handle the dependencies automatically was the way to go 👍
