### ISSUE TITLE
Serialize generic type when serializer is not needed for type argument

### ISSUE THREAD

**Issue by teenriot** [Kotlin/kotlinx.serialization#2868]
**What is your use-case and why do you need this feature?**

I want to serialize a generic type where the type parameter isn't relevant

```
typealias JavaClass = @Serializable(JavaClassSerializer::class) Class<*>

class JavaClassSerializer : KSerializer<Class<*>> {
    override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor("Class", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: Class<*>) = encoder.encodeString(value.name)
    override fun deserialize(decoder: Decoder) : Class<*> = Class.forName(decoder.decodeString())
}

@Serializable
data class Foo(val bar : JavaClass) //--> Serializer has not been found for type 'Any!'.
```

Alternative:

```
typealias JavaClass<T> = @Serializable(JavaClassSerializer::class) Class<T>

class JavaClassSerializer<T> : KSerializer<Class<T>> {
    override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor("Class", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: Class<T>) = encoder.encodeString(value.name)
    override fun deserialize(decoder: Decoder) : Class<T> = Class.forName(decoder.decodeString()) as Class<T>
}

@Serializable
data class Foo(val bar : JavaClass<*>) //--> Serializer has not been found for type 'Any!'.
```

**Describe the solution you'd like**

I think it should be possible to serialize generic types when there is no serializer for the type argument itself but you dont need it. 

I apologize in advance if this is already possible but i was not able to find a solution.

**Comment by pdvrieze** [comment]
This has issues with the Kotlin type system, even if the serializer is easily written. This is due to covariance. The serializer should work for `Class<Out Any>` where the deserializer works for `Class<in Nothing>`. You can make the `JavaClassSerializer` an object and do (with generic type warnings) casting to make things "work". Using a `deserializer` and `serializer` companion object values (returning the object after cast) you can make it available as explicit serializer. 

The following works for me:
```kotlin
typealias JavaClass = @Serializable(JavaClassSerializer::class) Class<out @Serializable(JavaClassSerializer::class) Any>

object JavaClassSerializer : KSerializer<Class<*>> {
    override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor("Class", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: Class<*>) = encoder.encodeString(value.name)
    override fun deserialize(decoder: Decoder) : Class<*> = Class.forName(decoder.decodeString())
}

@Serializable
data class Foo(val bar : JavaClass) //--> Serializer has not been found for type 'Any!'.
```

Note that this uses variance on the any which in this case is a val, so that is valid, but for a var would not work.
