### ISSUE TITLE
Some way to delegate to original KSerializer of arbitrary type

### ISSUE THREAD

**Issue by hqzxzwb** [Kotlin/kotlinx.serialization#2890]
Say, I want to deserialize/serialize some of class properties with a box, the type of the property may be anything:

```
// The json is {"bar": {"value": 1}}
data class Foo1(
  val bar: Int, // Box this property in json
)

// The json is {"bar": {"value": "abc"}}
data class Foo2(
  val bar: String, // Box this property in json
)
```

If I Follow instructions in [Delegating serializers](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#delegating-serializers), I need to write serializers separately:

```
object BoxedIntSerializer: KSerializer<Int> {
  // implementation, repeated for every type
}

object BoxedStringSerializer: KSerializer<String> {
  // implementation, repeated for every type
}

// The json is {"bar": {"value": 1}}
data class Foo1(
  val bar: @Serializable(BoxedIntSerializer::class) Int, // Box this property in json
)

// The json is {"bar": {"value": "abc"}}
data class Foo2(
  val bar: @Serializable(BoxedStringSerializer::class) String, // Box this property in json
)
```

I hope to have a way to avoid the repetition.

Following is what I tried but did not work, but I hope it to help making the point:

```
// The json is {"bar": {"value": 1}}
data class Foo1(
  val bar: Boxed<Int>, // Box this property in json
)

// The json is {"bar": {"value": "abc"}}
data class Foo2(
  val bar: Boxed<String>, // Box this property in json
)

typealias Boxed<T> = @Serializable(BoxSerializer::class) T // But Kotlin compiler does not allow this!

class BoxSerializer<T>(private val element: KSerializer<T>) {
  // implementation, not repeated, works for all types
}
```

Otherwise, I have to use a `Box` data class instead of a `Boxed` typealias, forcing users of the data class to read `value` property manually.

The use case is handmade to make the point clear. We have more complex use cases in real project, where the delegation logic is more complex than just boxing the data.

**Comment by pdvrieze** [comment]
The only way this could work is if the library/plugin allowed manually specified serializers to have constructors that take a type parameter (as if the type serialized is a generic type `Box<T>`). Effectively you want a serializer factory, rather than a serializer.

With the current system the workarounds are:
- _when hell freezes over_: get the people who thought it was a good idea to store the data this way to change the format to not do this
- Explicitly hold boxes (a `value class Box<T>(val value: T)`) - note that you could make this hidden from users, they only have access to additional getters/setters that are not boxed (data class primary constructors can be private), but it does require writing those delegates.
- Have custom serializers for the containers
- _least complex_: Create concrete instances as object: `object BoxedIntSerializer: BoxSerializer(Int.serializer)`
- _cleanest but "hardest"_: Create a fowarding/delegating format that, when it encounters a `@Box` annotation on an element will inject an appropriate box in:
  -  The serial descriptor used (for the attribute it needs the "box" type
  -  The (de)serializer called (it needs to call an appropriate BoxSerializer instance)
  -  The data type passed (`Json` - or other format) needs to work on `Box<T>` values, the delegating formats boxes/unboxes them

**Comment by sandwwraith** [comment]
You can save some copypaste by defining generic `class BoxSerializer<T>(private val dataSerializer: KSerializer<T>) : KSerializer<Box<T>>` (see https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#custom-serializers-for-a-generic-type). It can be used directly on `Boxed<Int>` or `Boxed<String>` type, or you can subclass it like `object BoxedIntSerializer: BoxSerializer(Int.serializer)` to be used directly.

Otherwise, a general feature you want is probably #292

**Comment by hqzxzwb** [comment]
Thanks for the instructions, I will go with the concrete-serializer way.
