### ISSUE TITLE
Compile-time safety for custom adapters?

### ISSUE THREAD

**Issue by fab1an** [Kotlin/kotlinx.serialization#29]
Is there any way to get compile-time safety with this library?

This was one of the reasons I wrote my own serialization library: https://medium.com/@spitzwegerich/generated-json-serialisation-for-kotlin-4470dabe40b8.

A main advantage is that I can be sure at compile-time that every (custom) type in every object has a proper adapter registered.

**Comment by sandwwraith** [comment]
Because every serializer on classes marked as `@Serializable` is resolved statically in compile-time by plugin, this library is type-safe. You also can use explicit form of `stringify(T, KSerializer<T>)` if you prefer, for example, for lists (see #27). 

One exception for now is user-registered external serializers. Because they are unknown at the time of compiling class itself, or there can be more than one serializer for specified class, their resolving is postponed until runtime (that's why you need to explicitly register them).

**Comment by sandwwraith** [comment]
Information about custom serializers updated in latest [doc](../blob/master/docs/custom_serializers.md)
