### ISSUE TITLE
Map(key: Long, value: Long) -> {"String", Long} and problem with encoder.encodeString()

### ISSUE THREAD

**Issue by avently** [Kotlin/kotlinx.serialization#368]
1. I have a map which have a key of type Long. This key for some reason becomes String after serialization (has quotes). Value with type Long becomes Long as expected. Example:
```
@Serializable
data class TestClass(val hashMap: HashMap<Long, Long>)
val test = TestClass(hashMapOf(123L to 321L))
println(Json().toJson(TestClass.serializer(), test))

{"hashMap":{"123":321}}
```

Is this a bug? How to avoid it?

2. In multiplatform project I have expect/actual declarations of BigDecimal. I created custom Serializer but the problem is that I didn't find a way to print BigDecimal without quotes. The code:

```
@Serializer(forClass = BigDecimal::class)
object BigDecimalSerializer: KSerializer<BigDecimal> {
    override val descriptor: SerialDescriptor = object: SerialClassDescImpl("BigDecimal") {
        override val kind: SerialKind = PrimitiveKind.DOUBLE
    }

    override fun serialize(encoder: Encoder, obj: BigDecimal) {
        encoder.encodeString(obj.toPlainString())
    }

    override fun deserialize(decoder: Decoder): BigDecimal {
        return BigDecimal(decoder.decodeString())
    }
}


@Serializable
data class TestClass(@Serializable(BigDecimalSerializer::class) val big: BigDecimal)
val test = TestClass(BigDecimal("10"))
println(Json().toJson(TestClass.serializer(), test))

{"big":"10"}
```

I can serialize it as Double but we know that Double will lose correct number. 
Would be great to have something like encoder.encodeString(quoted: Boolean = true)
What do you think about that? Maybe there is another way exists to get expected result?

**Comment by sandwwraith** [comment]
1. JSON spec says that a key in an object is always a `string` (https://tools.ietf.org/html/rfc7159#section-4). 

2. While spec says nothing about how big numbers could be, most clients (including JS) assume that number could not be more than [`abs(2^53-1)`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER), otherwise there is a possibility of precision loss. To transfer numbers greater than this one, string form is preferred. If you're sure that your numbers are less than max safe, you can use `encodeInt/decodeInt`

**Comment by avently** [comment]
@sandwwraith ok, thanks for explanation. Will use strings
