### ISSUE TITLE
YAML?

### ISSUE THREAD

**Issue by nkiesel** [Kotlin/kotlinx.serialization#4]
Any plans for that?

Also I'm still trying to figure out why I would use this instead of Jackson.  I guess x-platform is a big plus, but I'm currently using Kotlin exclusively on the server (i.e. JVM).

**Comment by sandwwraith** [comment]
We are not going to implement a lot of formats "out of the box", to keep runtime library small and easy-to-use. Instead, we try to encourage our users to write their own libraries for supporting different formats and build diverse ecosystem, because with serialization framework it become much easier. You can look at example project for JVM to find out how to write serializer which fits your needs (docs coming soon). If you publish a library which provides popular format for this framework, we'll include it in readme.

Regarding your second question: this serialization is reflection-less, so its main target are platforms on which Java Reflection API is unavailable or not desirable (Android, Kotlin/JS, Kotlin/Native). However, even on classic JVM targets you can obtain a huge performance improvement.

**Comment by nkiesel** [comment]
Thanks. Looking forward to the docs.

**Comment by sschuberth** [comment]
For people who come across this issue, by now there is https://github.com/charleskorn/kaml, but it only supports the JVM platform. Would still be great to have official YAML support also for Kotlin/JS.

**Comment by sandwwraith** [comment]
@sschuberth I saw that there's a multiplatform yaml too: https://github.com/Kotlin/kotlinx.serialization/tree/master/formats#yaml-multiplatform
