### ISSUE TITLE
Instructions on what to add to Gradle files/project structure files etc.

### ISSUE THREAD

**Issue by antonyfilochowski** [Kotlin/kotlinx.serialization#409]
Trying to setup/test serialization. The instructions are very confusing.
Added entries for plug in and dependencies. Received error from Android Studio.

ERROR: Failed to resolve: org.jetbrains.kotlinx:kotlinx-serialization-runtime-common:0.10.0

Could you please publish an unambiguous set of instructions that remove the guess-work?

**Comment by sandwwraith** [comment]
I think you've probably missed the repository

```gradle
repositories {
    jcenter()
    // artifacts are published to this repository
    maven { url "https://kotlin.bintray.com/kotlinx" }
}
``` 

part.

There is also a bunch of examples in `example-***` folders. The multiplatform sample will be added soon.

**Comment by Bzzz** [comment]
I'm also struggling getting this to work with my first android app thingy. First of all, both compile lines
`    compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"`
seem outdated as it throws "deprecated" warnings, should be
`    implementation"org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"`
right?

Second, upon using the very lines from the example, 
`val jsonData = Json.stringify(Data.serializer(), Data(42))`
throws an error (serializer() is marked in red in the code view):
`Unresolved reference: serializer
`


I have to place
`apply plugin: 'kotlinx-serialization'`
into the app/build.gradle (plugin 'kotlin' must not be added, duplicate with
`apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'`
) because if I add it to the main build.gradle (where classpaths are added), it throws an error and doesn't  work. That's not really obvious to a beginner.

Furthermore, you seem to define your own clean script, which collided with the one that I got in my example before. So I removed mine to get everything working. Yours doesn't force rebuilding, so I went back and forth with the apply plugin line as once it worked for the first time, it also worked in the wrong file, and it even worked when being completely omitted, which is clearly wrong. That changed on first clean/rebuild and would have really thrown me off track if I didn't look into that weird behaviour right away. Could you do without your own clean script maybe?

**Comment by sandwwraith** [comment]
@Bzzz Custom clean script is not required for setup. 

Applying plugin to the `app/build.gradle` instead of root one seems logical when you get familiar with basic gradle concepts: your application is in `app` _gradle subproject_, so you need to apply plugin for your app, not to the whole project. Moreover, serialization plugin have sense when applied after `kotlin` or `kotlin-android` plugin, and root build.gradle does not contain application of kotlin plugin.
