### ISSUE TITLE
Deprecate complex keys in map serializer and provide an additional opt-in option instead

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.serialization#424]
This feature currently is fragile, produces unexpected JSON format by default and interferes with other format-specific features in bizarre ways.

Such behaviour should require explicit opt-in

**Comment by davaya** [comment]
Please provide an example that breaks (illustrating fragility), an example the produces unexpected JSON (along with the example of what you do expect), and an example of interference with some other feature?

CBOR handles keys just like any other values; JSON can trivially do the same thing exactly as described in the documentation:

*"Note: because JSON doesn't support maps with keys other than strings (and primitives), Kotlin maps with non-trivial key types are serialized as JSON lists."*

If objects with complex keys are not being serialized as:

    [
        [key1, value1],
        [key2, value2]
    ]

then it would be unexpected.   If they are being serialized as documented, please describe the problems in more detail.

**Comment by sandwwraith** [comment]
It is serialized as `[key1, value1, key2, value2, ...]`. There is no problem in such format itself; however, it is a format extension which is not contained in the RFC or another languages implementations and therefore not obvious to the user (unless they read the documentation carefully and paid attention to the note). There is also a possibility that this is just a user's mistake since they try to serialize class which does not fully conform to JSON spec.

So, such behavior should be disabled by default. We have no plans to remove it because it is indeed helpful for transferring data when both parties use this library. It just would require an additional flag, as current `strictMode` or `unquoted` modes do.

**Comment by davaya** [comment]
This feature caught my eye because I am working on an information-centric serialization standard (see RFC 3444), and the top-down philosophy (design applications to do what they need to do, then use serialized data to communicate what applications need) aligns with that approach.   The bottom-up data-centric approach is to start with a data standard (such as JSON) and then restrict applications to not do anything that isn't directly supported by a specific data format.

I'm happy to hear that this isn't being deprecated.  I hope "disabled by default" means that the serialization function would have something like a "json-restricted=True" flag that would throw an error if given map data with non-string keys, and would not throw an error when given the same data and the caller opts in by passing "json-restricted=False" to the serializer.  (i.e. I hope it is a caller's runtime decision whether to opt in, not a compile time decision).

**Comment by davaya** [comment]
This feature caught my eye because I am working on an information-centric serialization standard (see RFC 3444), and the top-down philosophy (design applications to do what they need to do, then use serialized data to communicate what applications need) aligns with that approach. The bottom-up data-centric approach is to start with a data standard (such as JSON) and then restrict applications to not do anything that isn't directly supported by a specific data format.

I'm happy to hear that this isn't being deprecated.

**Comment by davaya** [comment]
This feature caught my eye because I am working on an information-centric serialization standard (see RFC 3444), and the top-down philosophy (design applications to do what they need to do, then use serialized data to communicate what applications need) aligns with that approach. The bottom-up data-centric approach is to start with a data standard (such as JSON) and then restrict applications to not do anything that isn't directly supported by a specific data format.

I'm happy to hear that this isn't being deprecated. CBOR, Protobuf, and Thrift (https://thrift.apache.org/docs/idl) all support keys of any type; JSON is the exception that does not.
