### ISSUE TITLE
1.3.30 generation limitations also apply when almost fully custom serialization is used

### ISSUE THREAD

**Issue by pdvrieze** [Kotlin/kotlinx.serialization#439]
The new generator has some limitations introduced. One of these is that serialization does no longer support properties without backing fields. In my code base I need some serious custom serialization/deserialization (partially due to having to handle cyclic references in immutable datastructures). There are some related things that the current rules limits:

 - A value that is stored as structure in Kotlin (for example QName) may be stored as two attributes in the data structure (namespace and localname). This worked with unbacked setters/getters that would do the mapping/adjusting.
 - Even with a custom serializer/deserializer it may be desirable to generate the serialdescriptor automatically, but ignore visibility and other issues that are no longer relevant with custom implementations.
 - Most critically, it is not possible to provide annotations for a manually created serial descriptor. The only alternative is to create a synthetic class that contains the annotations that you then extract the annotations from (a quite clumsy workaround)

**Comment by sandwwraith** [comment]
Can you attach a code sample to your use-case, please?

As far as I understood you, you want to serialize one entity with two `var`s without backing fields? We are looking into implementing special annotation which will make such things non-transient. However, it is unclear how to deserialize an object if it has `val` without a field, that's why they are prohibited.

SerialDescriptor still could be generated automatically, but it is impossible for it to know how your custom logic is implemented and which properties you've serialized.

 Annotations for custom serial descriptors were left out of scope intentionally because it seems there are no good use cases for such complex feature. If you have one, please tell us.
