### ISSUE TITLE
Property with explicit backing field gets serialized twice

### ISSUE THREAD

**Issue by woitee** [Kotlin/kotlinx.serialization#45]
If I try to serialize and deserialize the following structure:

```
@Serializable
open class GameObject(var x: Double = 0.0, var y: Double = 0.0) {
    var _corners:ArrayList<Int>? = null
    val corners: ArrayList<Int>
        get() {
            if (_corners == null) {
                _corners = arrayListOf(0, 1, 2, 3)
            }

            return _corners!!
        }
}
```

(e.g. by these methods)

```
val gameObject = GameObject()
val json = JSON.stringify(gameObject)
val objectCopy = JSON.parse<GameObject>(json)
```

It errors with a java.lang.NoSuchFieldError, because both "_corners" and "corners" are in the resulting JSON. I know this can be easily fixed by marking the "corners" property as transient, but shouldn't a property that only has a getter not be serialized implicitly?

**Comment by sandwwraith** [comment]
It depends on where and how do you want to use serialized class. If you want to share its internal state and pass it between tiers of your application (that's the main goal of this library) - then you're right, it's better to serialize only `_corners`.  Currently, we prefer to maintain more strict approach, so you need to write `@Transient` explicitly, as `@Optional` in #19. Later, this restrictions may be relaxed - it's always easier to remove restrictions rather than create new ones.

Another use-case for this is when you create external API and pass this objects to some other (usually third-party) application. In that case, you'd better serialize `corners` field and drop out backing `_corners`. However, if you want to restore object for some purpose, you need to write in `_corners` field. Seems it's hard to solve this problem with this library for now, and maybe later we'll develop mechanism for this.

**Comment by woitee** [comment]
Ok, thanks a lot for the reply. I also thought passing object to be reloaded by the same application (via network, persistent saving, or wherever) was the main objective of the library. But I can definitely design the class around this (implicit backing field or just going `@Transient`). I guess you can close this issue.

**Comment by sandwwraith** [comment]
@woitee reloading by the same application is essentialy almost the same: you also need share internal state

**Comment by woitee** [comment]
Yeah, that's why I thought that only the internal field will get serialized, the public in this case is "just" a get function. But I understand that this is difficult to decide and will crystallize as typical use-cases get formed.
