### ISSUE TITLE
Question: deserialize based on type, performance

### ISSUE THREAD

**Issue by coder82** [Kotlin/kotlinx.serialization#486]
Question, how do you deserialize data based on type?

Supposed you have a basic json structure like this, common to all types

`{
	"type": "someDataType",
	"data": {}
}`

The data field can change based on "type" but once "type" is read, then we'd know what "data" contains. Pretty basic.
Now I would parse parse with a basic type deserializer:

`@Serializable
data class Type(val type: String)`

Then test the type and proceed deserializing data based on that.

How's this with performance, ideally when we want to read just the type, it should not parse also the "data" part, which might be huge. Performance speaking, is this the best way to handle type based parsing?

**Comment by sandwwraith** [comment]
I assume yes, deserializer skips everything that found under "data". (But parser still performs tokenization to know where data block ends). 

>Then test the type and proceed deserializing data based on that.

I'm not sure what you mean by that, because once you read `type` field inside the object into `Type` class, the whole string under `data` is skipped and parser can't return back.
