### ISSUE TITLE
Delegated fieds are ommited duting serialization

### ISSUE THREAD

**Issue by majkrzak** [Kotlin/kotlinx.serialization#500]
**Describe the bug**
When object of Class with delegated property is serialized the delegated property is omitted.

**To Reproduce**

    @Serializable
    class Foo{
        val bar: Bar by ctx
        val lol: String = "asd"
    }

**Expected behavior**

    {
        "bar": {}
        "lol": "lol"
    }

**Environment**
 - Kotlin version: 1.3.40
 - Library version: 0.11.1
 - Kotlin platforms: JVM
 - Gradle version: Gradle 5.4.1-20190522110022+0000

**Comment by sandwwraith** [comment]
It is highlighted in the [documentation](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/examples.md):

> By default, only properties which have backing fields will be serialized and restored back.
...
Delegates are not supported and they're by default @Transient (since they do not have backing field)

Such a design decision was made because even if `Bar` is serializable, `ctx` is probably not. Therefore, on deserialization, you don't know what to insert to the `bar` field, because this field has a type of delegate, not the `Bar`. Since this delegate is also read-only, it is impossible to call setter with the deserialized value of `Bar`.

We have a design on the roadmap which would allow you to serialize properties by using getters and setters (currently this is done via direct field access for the performance and consistency sake). Then, it also would be possible to work with `var` delegates.

**Comment by camdenorrb** [comment]
Any updates on this?

**Comment by majkrzak** [comment]
It would rather not get fixed as long as assumption that "Serializable is also Unserializable" will be present in this project.

**Comment by shanshin** [comment]
Duplicates #1578
