### ISSUE TITLE
Serializing generics is not working

### ISSUE THREAD

**Issue by czeidler** [Kotlin/kotlinx.serialization#53]
Serializing the following `Container<Data>` class fails with:

```
INSTANCE
java.lang.NoSuchFieldException: INSTANCE
```

```
@Serializable
class Container<T>(val data: T)

@Serializable
class Data(val text: String)
```

**Comment by sandwwraith** [comment]
Error seems like you're trying to serialize container by simple `JSON.stringify(Container(Data(..)))`. Because of generic type erasure, this wouldn't work: On runtime, framework can't determine how to serialize data in container. Thus `Container` class does not have default (object) serializer, and thus there is no field `INSTANCE`.

Right way to do it is to create serializer explicitly: `JSON.stringify(Container.serializer(Data.serializer()), Container(Data(...)))`

**Comment by czeidler** [comment]
Ok thanks, I tried it (see below) but it still fails with the same error. What am I doing wrong? I'm using version 0.3.

Btw. IDEA is not recognising `Container.serializer` but only `Container::class.serializer`. However, if I use the later I can't do `Container::class.serializer(Data::class.serializer())` Why is that?    

```
@Serializable
class Container<T>(val data: T)

@Serializable
class Data(val text: String)

@Test
fun testGenerics() {
    val json = JSON.stringify(Container.serializer(Data.serializer()), Container(Data("test")))
    val parsed = JSON.parse<Container<Data>>(json)
    assertEquals("test", parsed.data.text)
}
```

**Comment by sandwwraith** [comment]
`JSON.parse` also requires explicit serializer in your case - generic arguments are not reified, even if the function reified itself :( So in your case you should end with something like

```kotlin
val boxedDataSerial = Container.serializer(Data.serializer())
val json = JSON.stringify(boxedDataSerial, Container(Data("test")))
val parsed = JSON.parse(boxedDataSerial, json)
assertEquals("test", parsed.data.text) // ok
```

Yes, for now IDEA experience is slightly poor because it don't recognize some synthetic functions. You can improve it by following this instructions: https://github.com/Kotlin/kotlinx.serialization#working-in-intellij-idea

**Comment by czeidler** [comment]
Ok thanks this works now!

I don't understand the internals but it still looks a bit cumbersome, i.e. since I can't do T.serializer() I have to provide the correct serializer for each concrete type. Or is the there a generic way to do it?

**Comment by sandwwraith** [comment]
If you have non-generic class (say, `MyData(val a: Container<Data>)`, you can use simple `MyData.serializer()`. However, if your class has type arguments, you have to provide serializers explicitly for each generic type.

In some observable future, we are going to invent mechanism such compiler could also insert serializers on call-site, not only in internal serialization calls. This should make things easier.

**Comment by coder82** [comment]
Are the serializer classes threadsafe?

**Comment by sandwwraith** [comment]
@coder82 They must be stateless. How this question is related to the issue?

**Comment by antanas-arvasevicius** [comment]
Hi,
I also concerned about thread safety of serializers? Especially for
PolymorphicSerializer. We are getting strange data corruptions during
serialization when parallel threads do serialization simultaniously. And
always getting corrupted json just after generic field where
PolymorphicSerializer kicks in. Anyone have similiar issues?

**Comment by pdvrieze** [comment]
The JSON serializer is stateful. You cannot really reuse it and it doesn't have synchronization to coordinate access (writing from different threads). You want to create one at least per thread, but probably per operation. Also remember that serialization is not atomic as outputstreams are not (if they are threadsafe to begin with) but also due to the fact that the json serializer writes in fragments smaller than a full element.

**Comment by antanas-arvasevicius** [comment]
Problem is that "PolymorphicSerializer" is singleton object... and I cannot have multi instances of it.
Now It's possible to create new serializers for each serialization action but impossible for generics (i.e. EventLog.serializer(PolymorphicSerializer)).
Or we didn't understand kotlinx.serialization design. Shouldn't (Is?) KSerializer<T> be thread-safe and immutable?

**Comment by pdvrieze** [comment]
PolymorphicSerializer has no state so is threadsafe, but the generated serializers for classes have no specific thread support. That is, if you change the object while it is being serialized this will likely lead to incorrect values. Custom serializer code can of course add locks where appropriate or be externally synchronized.

**Comment by sandwwraith** [comment]
@antanas-arvasevicius @coder82 see #139, there is a discussion about thread-safety in json. Try to replace `JSON.nonstrict` with `JSON(nonstrict = true)` and check if it works correctly.

**Comment by coder82** [comment]
hi Sand, it worked... I saw you committed a fix on master, may I use that directly?

**Comment by elkasvirElka** [comment]
> If you have non-generic class (say, `MyData(val a: Container<Data>)`, you can use simple `MyData.serializer()`. However, if your class has type arguments, you have to provide serializers explicitly for each generic type.
> 
> In some observable future, we are going to invent mechanism such compiler could also insert serializers on call-site, not only in internal serialization calls. This should make things easier.

Can you give an example, please?
