### ISSUE TITLE
Polymorphic get json if type can't be found

### ISSUE THREAD

**Issue by vanniktech** [Kotlin/kotlinx.serialization#608]
I've got a data structure where certain keys are already mapped out. In case I get a new type that I can't parse yet I want to get a reference to the raw JSON, persist it and with an app update be able to parse it correctly.

Currently there's no way to get the raw JSON using `SerializersModule { polymorphic() {} }`

This might be similar to some of the backup feature requests:

https://github.com/Kotlin/kotlinx.serialization/issues/593
https://github.com/Kotlin/kotlinx.serialization/issues/448

This could look something like this:

```kotlin
@Serializable sealed class Data {
  @Serializable @SerialName("foo") data class Foo(
    ..
  ) : Data()
  @Serializable @SerialName("data") data class Data(
    ..
  ) : Data()
  @SerializableRaw data class Raw(
    val json: String
  ) : Data()
}
```

Where the Raw class can be instantiated and used to pass the json as a string.

**Comment by pdvrieze** [comment]
To make this work you would need to put it on a `Map<String, JsonElement>` type property as there can be arbitrary unsupported properties.

**Comment by Whathecode** [comment]
I do exactly this with [a custom `UnknownPolymorphicSerializer`](https://github.com/cph-cachet/carp.core-kotlin/blob/develop/carp.common/src/commonMain/kotlin/dk/cachet/carp/common/serialization/UnknownPolymorphicSerializer.kt) I wrote (I'm still looking for a better name for this, so suggestions are welcome! ;p). My use case was having a back-end able to handle unknown deriving types seamlessly, still being able to access base properties. For now, this only works for Json, though, since it relies on substring manipulation.

How to set this up with my current solution [can be seen in the unit tests](https://github.com/cph-cachet/carp.core-kotlin/blob/develop/carp.common/src/commonTest/kotlin/dk/cachet/carp/common/serialization/UnknownPolymorphicSerializerTest.kt).

In short, for each base type you want to allow unknown extending types for, you need to set up a 'wrapper' class which is initialized from the raw serialization data and extracts base properties. You then need to create an 'UnknownPolymorphicSerializer' for this base type, which needs to be applied wherever you want to allow for unknown extending types during serialization.

```
    object UnknownBaseTypeSerializer : KSerializer<BaseType>
        by createUnknownPolymorphicSerializer( { className, json, serializer -> CustomBaseType( className, json, serializer ) } )
```

It has been on my backlog to try to integrate this fully into kotlinx.serialization in a PR. This would probably involve a new type of annotation (e.g., @UnknownPolymorphic). Likely this could also be done cleaner if some stuff is taken care if in the compiler plug in (is this open source?). Would there be an interest in this?

**Comment by vanniktech** [comment]
> To make this work you would need to put it on a `Map<String, JsonElement>` type property as there can be arbitrary unsupported properties.

That would be fine for me as well.

> It relies on a platform-specific implementation for [JVM](https://github.com/cph-cachet/carp.core-kotlin/blob/develop/carp.common/src/jvmMain/kotlin/dk/cachet/carp/common/serialization/UnknownPolymorphicSerializer.kt) [](/cph-cachet/carp.core-kotlin/blob/HEAD@{2019-11-21T22:17:05Z}/carp.common/src/jvmMain/kotlin/dk/cachet/carp/common/serialization/UnknownPolymorphicSerializer.kt) and [JS](https://github.com/cph-cachet/carp.core-kotlin/blob/develop/carp.common/src/jsMain/kotlin/dk/cachet/carp/common/serialization/UnknownPolymorphicSerializer.kt) [](/cph-cachet/carp.core-kotlin/blob/HEAD@{2019-11-21T22:17:05Z}/carp.common/src/jsMain/kotlin/dk/cachet/carp/common/serialization/UnknownPolymorphicSerializer.kt).

That's a bummer as I also do require iOS support. Maybe not for now but for sure in 2020 Q1.

> Would there be an interest in this?

You've got my back.

**Comment by sandwwraith** [comment]
It should be possible with the next release, where changes from #726 will become available. There is an example in test data showing how to achieve that using `JsonTransformingSerializer` + `defaultPolymorphic`: https://github.com/Kotlin/kotlinx.serialization/pull/726/files#diff-dc18ae254803a976148b591b04beeed4R49
