### ISSUE TITLE
Serialization with kotlinx.collections.immutable/persistent classes

### ISSUE THREAD

**Issue by carterhudson** [Kotlin/kotlinx.serialization#635]
I have a class like so:
```
@Serializable
data class SomeClass(
  val someMap: PersistentMap<String, SomeModel> = persistentMapOf(),
  val someList: PersistentList<String> = persistentListOf()
) 
```
and I get the following error when I try to serialize it:
```
kotlinx.serialization.SerializationException: class kotlinx.collections.immutable.implementations.persistentOrderedMap.PersistentOrderedMap is not registered for polymorphic serialization in the scope of class kotlinx.collections.immutable.PersistentMap
        at kotlinx.serialization.PolymorphicKt.throwSubtypeNotRegistered(Polymorphic.kt:149)
```
I don't think I can use a polymorphic serializers module since I don't own / can't annotate the classes in question. Is there a way I can serialize these fields? Perhaps a way to specify that `PersistentMap` and `PersistentList` should just use the serializers for `Map` and `List` respectively?

**Comment by Dominaezzz** [comment]
Yes! But you'll have to write a (probably very thin) custom serializer.

You could potentially do
```
@Serializable
data class SomeClass(
  val someMap: Map<String, SomeModel> = persistentMapOf(),
  val someList: List<String> = persistentListOf()
) 
```
but that has it's complications when **de**serializing. Since it won't know to create the right type of `List` or `Map`. (Unless you don't need to deserialize.....)

After you write your custom serializer, you can then do,
```
@Serializable
data class SomeClass(
  @Serializable(with=MyMapSerializer::class)
  val someMap: PersistentMap<String, SomeModel> = persistentMapOf(),
  @Serializable(with=MyListSerializer::class)
  val someList: PersistentList<String> = persistentListOf()
)
```
More information about the annotations [here].(https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/custom_serializers.md#useserializers-annotation).

For writing your custom serializers, [this](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/custom_serializers.md#about-generic-serializers), [this](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/custom_serializers.md#external-serializers-for-library-classes) and especially [this](https://github.com/Kotlin/kotlinx.serialization/blob/4f39fc70f70021f16de705e3027d0c507c59a17a/runtime/commonMain/src/kotlinx/serialization/json/JsonElementSerializer.kt#L167), will come in very handy.

Let me know how it goes.

**Comment by carterhudson** [comment]
Perfect, thank you!
