### ISSUE TITLE
Why SerializationStrategy is contravariant?

### ISSUE THREAD

**Issue by AlexanderShniperson** [Kotlin/kotlinx.serialization#706]
**What is your use-case and why do you need this feature?**
impossible to compile project, error at `Serializer` line `31` the reason `Cannot infer type parameter`
https://github.com/AlexanderShniperson/KotlinNativeSerialization

**Describe the solution you'd like**
make `kotlinx.serialization.SerializationStrategy` as `invariant` as it does for `kotlinx.serialization.DeserializationStrategy`

**Comment by sandwwraith** [comment]
The problem here is not with variance. It's because you're trying to serialize `MessageBase` with serializer for `SomeData`, which won't obviously work with other `MessageBase`'s inheritors. You have to apply unchecked cast, because information compiler can't be sure that it is exactly `SomeData` and not the other inheritor.

Btw, have you seen  https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/polymorphism.md ? It looks like out-of-box polymorphism can solve your problem

**Comment by AlexanderShniperson** [comment]
@sandwwraith yes i see them, but i don't like it, because it is add extra bytes to serialized message and also as it described it is based on deep reflection

**Comment by sandwwraith** [comment]
Can you clarify what makes you think that default polymorphism is based on deep reflection? I've tried to state in the docs that it does not use reflection, only `KClass` comparisons and pre-registered modules

**Comment by AlexanderShniperson** [comment]
> Polymorphic serialization is usually a very complicated and dangerous feature due to the amount of reflection it brings and security concerns you should address in your application (like "what if you accidentally load or deserialize a class that is not allowed to be in this part of the program").

source here: https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/polymorphism.md

**Comment by sandwwraith** [comment]
Next paragraph starts with `To overcome these drawbacks` and describes our solution to stated problem, which does not bring nor reflection, nor security concerns. Sorry for consufion

**Comment by AlexanderShniperson** [comment]
ok then i need to do some performance tests, thanks
