### ISSUE TITLE
[Question] Can't figure out sealed class polymorphism with protobuf

### ISSUE THREAD

**Issue by camdenorrb** [Kotlin/kotlinx.serialization#719]
Target code:

```
//@Polymorphic
@Serializable
sealed class Request {

    @Serializable
    @SerialName("StockHistory")
    data class StockHistory(
        @Polymorphic @Required val ticker: String,
        @Polymorphic @Required val hours: Int
    ) : Request()



    companion object {
        val protoBuf = ProtoBuf(SerializersModule {
            polymorphic(Request::class) {
                addSubclass(StockHistory.serializer())
            }
        })
    }
    
}
```

Main:
```
println(Request.protoBuf.load<Request>(Request.protoBuf.dump(Request.StockHistory("BTCs", 10))))
```

This results in this error: `class kotlin.String is not registered for polymorphic serialization in the scope of class kotlin.String`

I can't seem to piece together what I'm doing wrong, I also tried doing this without the experimental "ImplicitReflectionSerializer" stuff, results in the same issue.

Any help is greatly appreciated.

**Comment by Dominaezzz** [comment]
Try removing the `@Polymorphic` (and also `@Required`, since it's implied) annotation.
Also, remove this,
```
polymorphic(Request::class) {
    addSubclass(StockHistory.serializer())
}
```

If none of these work for you, then provide the versions of Kotlin, IDE, plugin and runtime library you are using.

**Comment by camdenorrb** [comment]
@Dominaezzz Didn't change anything unfortuantly

Kotlin 1.3.61
Intellij 2019.3
org.jetbrains.kotlinx:kotlinx-serialization-runtime:0.14.0

**Comment by Dominaezzz** [comment]
Upon further searching, I don't think ProtoBuf supports polymorphism. It has only been implemented for JSON in PRs. I can't find PR or code for ProtoBuf polymorphism.

**Comment by camdenorrb** [comment]
https://github.com/Kotlin/kotlinx.serialization/blob/4f39fc70f70021f16de705e3027d0c507c59a17a/runtime/commonTest/src/kotlinx/serialization/protobuf/ProtobufPolymorphismTest.kt

?

**Comment by sandwwraith** [comment]
You need to remove `@Polymorphic @Required` from `val ticker` and `hours`, because you don't want to serialize _ticker_ and _hours_ polymorphically, right? String always has one implementation, since it is a final class. 

Also, correct form of dump would be `Request.protoBuf.dump(Request.serializer(), Request.StockHistory("BTCs", 10))` (or `dump<Request>(...)`) – you need to use `Request.serializer()`, not `Request.StockHistory.serializer()`, since only the sealed class serializer knows about all hierarchy. 

Unfortunately, due to #721 bug, you may experience `java.lang.ArrayIndexOutOfBoundsException: 1` with a [funny] workaround of adding additional class. So final correct code would look like:

```kotlin
@Serializable
sealed class Request {

    @Serializable
    @SerialName("StockHistory")
    data class StockHistory(
        val ticker: String,
        val hours: Int
    ) : Request()

    @Serializable
    class Unused: Request()

    companion object {
        val protoBuf = ProtoBuf()
    }
}

println(Request.protoBuf.load<Request>(Request.protoBuf.dump<Request>(Request.StockHistory("BTCs", 10))))
// prints StockHistory(ticker=BTCs, hours=10)
```

**Comment by camdenorrb** [comment]
@sandwwraith Thank you so much! The array out of bounds exception really threw me off when I got it from experimenting. Glad this is all clear now.
