### ISSUE TITLE
The results of JsonObject.toSting vary from platform to platform

### ISSUE THREAD

**Issue by roths** [Kotlin/kotlinx.serialization#757]
version:0.14.0
json data struct:
status_code -> "0"

when i  use toString(), i got {"status_code":0} in android，but  {"status_code"=0} in IOS.

**Comment by qwwdfsad** [comment]
Could you please provide a self-contained reproducer?
E.g. `println(Json.parseJson("""{"a": 1}"""))` properly prints `{"a":1}`

**Comment by roths** [comment]
The code for the blue area

**Comment by roths** [comment]
![1584092422349](https://user-images.githubusercontent.com/7519916/76609079-bca66800-6551-11ea-857f-6c8fdf4ad8c6.jpg)
The code for the blue area：
```
val test = JsonObject(mutableMapOf())
test.put("data", JSON.instance.parseJson("""{"a": 1}"""))
LogUtil.d("test", test.toString())
```
The first red area that swift prints, converts the map to a string and passes it to the cross-platform library written in Kotlin, the second red area is the cross-platform library that converts the string to a Jsonobject and then put the Jsonobject into another Jsonobject. The output becomes "="

**Comment by sandwwraith** [comment]
But the code in the blue area outputs with ":"

So `LogUtil.d("test", test.toString())` becomes `D/test: {"data":{"a":1}}`

I believe error is somewhere in the other place

**Comment by roths** [comment]
Is it because of the transformation between objc string and kotlin string？
Is there any logical branch that causes output "="？

**Comment by sandwwraith** [comment]
I don't know exactly what 'D/JsBridgeModule' means. You can verify by yourself that toString method is not platform dependent and does not contain any `=` symbol: https://github.com/kotlin/kotlinx.serialization/blob/22c712ad3e890c9e95b56f6bdc8876e4cc3f7c6d/runtime/commonMain/src/kotlinx/serialization/json/JsonElement.kt#L286

**Comment by roths** [comment]
![image](https://user-images.githubusercontent.com/7519916/76697404-c5be4300-66d1-11ea-987f-4b5f0441f98a.png)

here is the code in swift. the output contain `=` symbol

**Comment by sandwwraith** [comment]
It looks like it is related to `NSLog/description` internal mechanisms which list keys differently for NSDictionary and  AnyObject. Btw, your first example is also incorrect JSON since it is not an array, and there should be `{}` instead of `[]`.

AFAIR, Kotlin's `toString()` is not mapped to Swift's `description`, so try to use `.toString()` method instead.

**Comment by sandwwraith** [comment]
As a workaround, you can always write a `.jsonToString` method by yourself.

**Comment by sandwwraith** [comment]
I finally managed to reproduce it and turns out that this is a problem with Kotlin/Swift interop design: https://github.com/JetBrains/kotlin-native/issues/3991

There's also an easier workaround: declare `fun asString(element: JsonElement) = element.toString()` and use it instead of the description.

**Comment by qwwdfsad** [comment]
Please keep track of the issue in K/N repository
