### ISSUE TITLE
parse JsonArray and JsonElement.toString performance JVM vs native iosX64 vs swift

### ISSUE THREAD

**Issue by standsed** [Kotlin/kotlinx.serialization#833]
There is quite big performance difference when parsing large json string in JVM and native iosX64
`Json.parseJson(jsonString) as JsonArray`
also serializing lot of JsonElement's back toString
`JsonElement.toString()`

Platform | String size | Json.parseJson (millis) | JsonElement.toString (millis)
---------|------------|------------------------|------------------------------
JVM | 940b | 0.169734 | 0.159045
native iosX64 | 940b | 0.119081 | 0.153322
swift | 940b | 0.086647 | 0.097023
JVM | 1Mb | 16.104879 | 23.704069
native iosX64 | 1Mb | 160.062425 | 170.953403
swift | 1Mb | 24.019624 | 27.368558 
JVM | 5.7Mb | 79.185944 | 182.276485
native iosX64 | 5.7Mb | 1835.876132 | 1353.416678
swift | 5.7Mb | 140.198165 | 160.042163 

[Kotlin and swift test cases](https://github.com/standsed/NativeSerializationPerformanceRepro)
gist of kotlin test case
```
    fun exec(json: String) {
        var jsonArray: JsonArray
        val t = measureTime {
            jsonArray = Json.parseJson(json) as JsonArray
        }
        println("parse as JsonArray ${t.inMilliseconds} millis")

        var jsons: List<String>
        val t2 = measureTime {
            jsons = jsonArray.map {
                it.toString()
            }

        }
        println("map ${jsons.count()} JsonElement to List<String> ${t2.inMilliseconds} millis")
    }
```

1. Judging from JsonElement.toString, which is basically iterating over map entries and appending key-values to StringBuilder, should we expect this performance difference anywhere where large amount of operations over strings are done?
2. There is some effect between debug and release ios framework build type, later being 2.5 times faster on 5.7Mb case. 
Are there more such things that can be done to improve native performance?

**Comment by sandwwraith** [comment]
I believe that this is more of a Kotlin/Native runtime issue rather than a particular implementation in this library. Since K/N is still in beta, there's a work in progress on performance and it should get better with each new release.

Indeed, release builds are compiled with LLVM optimization enabled. As far as I remember, release builds should be fastest without a need to fine-tune compiler options.

**Comment by LepilkinaElena** [comment]
So do results in table for `native iosX64` correspond to release or debug build?

**Comment by standsed** [comment]
> So do results in table for `native iosX64` correspond to release or debug build?

Tests were run via gradle task iosX64Test.
I guess it's debug because parsing 5Mb json string in swift using k/n framework with exec function above:
debug 2.702452537 seconds
release 1.113707807 seconds

**Comment by LepilkinaElena** [comment]
@standsed thank you. I had a look on your examples. 
Small note: tests are always built with (`-g`) and without many optimizations in order to provide the most consistent debug info and faster compilation. If you are interested in measuring execution time you have to use optimized build (`-opt` compiler flag).
Also used measurement procedure isn't right to get exact data and comparison, but it's understandable that you need rough estimate. 

I checked it on 1.4-M1, if use experimental option and change allocator there also can be seen some improvement (pay attention this option is experimental, it's possible that there can be some problems). These changes https://github.com/LepilkinaElena/NativeSerializationPerformanceRepro/commit/232c64011d712ad125b83c175c44719315b149d0 allow to get next results on iosX64
```
parse as JsonArray 0.11109 millis
map 1 JsonElement to List<String> 0.037651 millis
2nd run
parse as JsonArray 0.035417 millis
map 1 JsonElement to List<String> 0.042629 millis
parse as JsonArray 35.386465 millis
map 909 JsonElement to List<String> 37.355665 millis
2nd run
parse as JsonArray 53.093898 millis
map 909 JsonElement to List<String> 33.530729 millis
parse as JsonArray 622.729589 millis
map 5171 JsonElement to List<String> 368.205081 millis
2nd run
parse as JsonArray 695.425174 millis
map 5171 JsonElement to List<String> 357.580647 millis
```

Also I checked one commit that was created to solve similar performance problem https://github.com/JetBrains/kotlin-native/commit/cfca81cc9d36956ad90912d1c7cc3d4ff6caf009
It'll be in `1.4-M3` and it helps to speed up 5Mb Json.parseJson up to ~250 millis and JsonElement.toString to ~200 millis.

Of course, we'll continue do some changes to speed up generated code by K/N.
