### ISSUE TITLE
Annotation with vararg parameters is compiled incorrectly

### ISSUE THREAD

**Issue by Him188** [Kotlin/kotlinx.serialization#836]
**Describe the bug** 
`@SerialInfo` annotations with `vararg` are generated incorrectly with single array element casted to an array.

**To Reproduce**
```kotlin
@SerialInfo
@Target(AnnotationTarget.FIELD, AnnotationTarget.PROPERTY)
annotation class Comment(vararg val lines: String)

@Serializable
data class CommentTest(
    @Comment("testA")
    val value1: String,
    @Comment("testA")
    val value2: String
)

fun main() {
    Json(JsonConfiguration.Stable).stringify(CommentTest.serializer(), CommentTest("", ""))
}
```

Decompiled generated serializer: 
```java
 SerialClassDescImpl var1 = new SerialClassDescImpl(...)
 var1.addElement("value1", false);
 var1.pushAnnotation(new Impl((String[])"testA")); // !! String casted to Array
 var1.addElement("value2", false);
 var1.pushAnnotation(new Impl((String[])"testA"));
```

**Expected behavior**
The code complete successfully

**Environment**
 - Kotlin version: 1.3.72 MPP
 - Library version: 0.20.0
 - Kotlin platforms: MPP library, running on JVM
 - Gradle version: 6.3

**Comment by sandwwraith** [comment]
This is no longer a problem for the new JVM IR compiler in 1.5.0

**Comment by Vampire** [comment]
What does that mean @sandwwraith?
I try to use 1.5.1 on Kotlin 1.7.10 (pinned due to usage in a Gradle plugin for Gradle 7.6.4).
And there it happens just the same.
I use xmlutil and try to use the `XmlBefore` annotation which has a `vararg String` parameter.
If I have one value, it is compiled to a `String` casted to a `String[]`.
If I have multiple values, it does not even compile.

**Comment by Vampire** [comment]
I solved my use-case differently, but shouldn't this still be fixed in KxS to either support varargs, or at least give a meaningful error if varargs are found instead of a class cast exception at runtime for one value or a not so meaningful compile error for multiple values?

**Comment by pdvrieze** [comment]
@Vampire This problem is a compiler plugin issue (generates incorrect code). There seems to be little the library can do about it. The non-workaround answer is to use a modern compiler (possibly told to generate code targeting older kotlin versions/kotlin library versions). Note that the modern compiler can target/be compatible with older standard library versions (if told to).

**Comment by Vampire** [comment]
But isn't the compiler plugin part of the library and you said it should work with IR and 1.5.0.
As I'm using 1.5.1 and IR should be used by Kotlin 1.7.10, I wonder that it still fails.

**Comment by Vampire** [comment]
Ah, no the compiler plugin is not part of KxS it seems, sorry.
With Kotlin 1.8.20 and xmlutil 0.86+ it compiles fine.
With Kotlin 1.7.10 and xmlutil 0.85.0 which was the last that was compiled with 1.8.10 it also compiles fine.

**Comment by sandwwraith** [comment]
In [my comment](https://github.com/Kotlin/kotlinx.serialization/issues/836#issuecomment-844209176) 1.5.0 refers to Kotlin version.

**Comment by Vampire** [comment]
Oh, I see, then I misinterpreted, but the outcome is the same, I use a newer version and it still happens. :-)

**Comment by sandwwraith** [comment]
@Vampire Can you please file a new issue with a reproducer?

**Comment by Vampire** [comment]
As I said, it happened with Kotlin 1.7.10 and xmlutil compiled with 1.8.20.
It does not happen with Kotlin 1.7.10 and xmlutil compiled with 1.8.10.
And it does not happen with Kotlin 1.8.20 and xmlutil compiled with 1.8.20.

So I now think this is simply a backwards incompatibility when compiled with too new Kotlin and probably not something that needs fixing?

**Comment by sandwwraith** [comment]
Yes, looks like it. Alright then!
