### ISSUE TITLE
Json.parseOrNull fun

### ISSUE THREAD

**Issue by AltmanEA** [Kotlin/kotlinx.serialization#839]
**What is your use-case and why do you need this feature?**

For simplicity of a JSON.parse using.

**Describe the solution you'd like**

`fun <T> parseOrNull(
    deserializer: DeserializationStrategy<T>,
    string: String
) =
    try {
        Json.parse(
            deserializer,
            string
        )
    } catch (e: Throwable) {
        null
    }`

**Comment by qwwdfsad** [comment]
There are a lot of reasons why parsing could fail: invalid JSON input, improperly configured JSON instance, failed validation of the instance of the class etc.
Providing a catch-all method (it even ignores OOM and SOE!) is a no go for us: it creates a temptation to use it, but masks potentially dangerous problems that might have otherwise indicated bugs in the business logic of the application. We don't want to encourage usage of such API.

The extension is pretty straightforward to add in your own project if you want to (tho it's recommended to catch `SerializationException` instead).

Closing as won't fix
