### ISSUE TITLE
Android Native Targets Feature Request

### ISSUE THREAD

**Issue by senagbe** [Kotlin/kotlinx.serialization#862]
**What is your use-case and why do you need this feature?**
We are trying to share code between multiple platforms. The common code is buildable for desktop and ios mobile native but not natively for Android.

We wish to be able to build an Android library which also has uses kotlinx.serialization in its native code.

**Describe the solution you'd like**
Add Android Targets for Arm32/Arm64 and X86/X86_64

**Comment by senagbe** [comment]
@sandwwraith is there anything stopping us from submitting a PR for this?

**Comment by senagbe** [comment]
@qwwdfsad where can I find the tests and TeamCity mentioned here? I'm happy to put some work in to make sure the tests pass https://github.com/Kotlin/kotlinx.serialization/pull/871#discussion_r444076074

**Comment by qwwdfsad** [comment]
Thanks for your enthusiasm @senagbe!

Unfortunately, adding a corresponding target and tweaking TeamCity configuration is not enough.
It also requires dedicated TeamCity agents (whether bare-metal or properly virtualized) that is capable of running arm32.

Configuring such agents requires serious effort from our build team (in order to make them consistent, cloneable, observable), and, frankly speaking, their resources are seriously limited right now, especially in the face of upcoming Kotlin 1.4 release. Long story short, _currently_ we neither have an infrastructure to test and release arm binaries **on a regular basis** nor resources to establish this infrastructure. We'll return to this problem right after Kotlin 1.4 post-release activities.

For now, the easiest solution will be to publish these binaries on your own side, either in your organization bintray on directly in maven local of the target machine (if you are going to build your native app right there). 
It can be achieved by adjusting serialization version in `gradle.proprerties` and adding the corresponding target to `native_mpp.gradle`. Feel free to ask any questions if you are struggling with building it locally.

**Comment by senagbe** [comment]
@qwwdfsad thanks for this, please let m know what the status of this is as we are post 1.4.0. I'm interested to know what kind of resources are required and if there is any way I can help.

**Comment by VVictorWang** [comment]
@qwwdfsad Hello. I also need this feature urgently. I'm wondering is there any plan for this feature? Thanks a lot.

**Comment by TheTreek** [comment]
Has there been any updates on this? It's been quite a while.

**Comment by sandwwraith** [comment]
These targets will be added in 1.5.1
