### ISSUE TITLE
Protobuf de-serialization optimization

### ISSUE THREAD

**Issue by palkatap** [Kotlin/kotlinx.serialization#890]
I was experimenting with kotlin serialization.
I compared the performance of reading/writing of a huge java object with json and protobuf. I was surprized that the two are almost the same in terms of speed. I was expecting that protobuf will be much faster.
I ran a test program with java flight recorder. I can't really evaluate the result, but I can send the generated jfr file to you, if you need it.

I found a class where you can do a minimal optimization:
  kotlinx.serialization.protobuf.ProtoBuf$ProtobufDecoder
The field curTag of this class is private and is never returned. I think, using two separate Int variables instead of Pair class could improve the performance:
- no need to create the Pair class
- on JVM no need to create the Integer instance, it could be also int type

Another small issue: the return value of the private method readTag() is never used.

**Comment by sandwwraith** [comment]
Hi,
Thanks for your interest and time. You are right, there's a room for improvement in protobuf. The library is constantly evolving, so there may be differences in the actual codebase vs latest release version. In particular, optimizations you've mentioned are already committed to the `dev` branch (e.g. https://github.com/Kotlin/kotlinx.serialization/blob/dev/formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/ProtoTypes.kt -- bit mask instead of Pair). Also, we'll continue to work on it to bring more optimizations.

**Comment by qwwdfsad** [comment]
It's all fixed and protobuf will be much faster in the next release https://github.com/Kotlin/kotlinx.serialization/issues/216#issuecomment-612869396

Closing as the duplicate, thanks for the report!
