### ISSUE TITLE
 Can't locate argument-less serializer for class a. For generic classes, such as lists, please provide serializer explicitly.

### ISSUE THREAD

**Issue by prudhvir3ddy** [Kotlin/kotlinx.serialization#946]
**Describe the bug**

it's working normally in the debug version of the app but when I turn on proguard I am getting this error

`java.lang.IllegalArgumentException: Unable to create @Body converter for class c.a.a.c.e.d.a (parameter #1)`

`Caused by: g.b.v: Can't locate argument-less serializer for class a. For generic classes, such as lists, please provide serializer explicitly.`

my data class: 

```
@Serializable
data class ApiError(
  @SerialName("error") val error: Error
)

@Serializable
data class Error(
  @SerialName("code") val code: Int,
  @SerialName("timestamp") val timestamp: String,
  @SerialName("path") val path: String,
  @SerialName("method") val method: String,
  @SerialName("message") val message: List<String>
)

```

I am guessing maybe I need some extra statements in proguard to keep classes that generated for the List serialization, can someone please help me what it's about. 

**Environment**
 - Kotlin version: [e.g. 1.3.71]
 - Library version: [e.g. 0.20.0]
 - Kotlin platforms:  JVM
 - Gradle version: 6.3
 - IDE version (if bug is related to the IDE) [Android Studio 4.0]

**Comment by sandwwraith** [comment]
Hi, have you tried applying proguard rules from here: https://github.com/Kotlin/kotlinx.serialization#androidjvm ?

**Comment by prudhvir3ddy** [comment]
@sandwwraith yes I applied them

**Comment by MJegorovas** [comment]
Getting similar error (proguard rules applied):
`java.lang.RuntimeException: Unable to start activity ComponentInfo{...activities.LActivity}: k.a.t: Can't locate argument-less serializer for class r. For generic classes, such as lists, please provide serializer explicitly.`

`Caused by: k.a.t: Can't locate argument-less serializer for class r. For generic classes, such as lists, please provide serializer explicitly.`

Exception class:
`@Serializable
data class Version(@SerialName("android") val version: Int)`

**Comment by prudhvir3ddy** [comment]
thanks, @MJegorovas figured out the issue.
