### ISSUE TITLE
ProtoBuf's example code cannot be used with single name imports

### ISSUE THREAD

**Issue by OliverO2** [Kotlin/kotlinx.serialization#954]
**What is your use-case and why do you need this feature?**

This code taken from examples in `ProtoBuf.kt` (version `1.0-M1-1.4.0-rc`) would not compile if single-name imports are used:
```
import kotlinx.serialization.Serializable
import kotlinx.serialization.protobuf.ProtoBuf

@Serializable
data class MyMessage(val first: Int, val second: Int = 0, val third: Int = 42)

val encoded2 = ProtoBuf(encodeDefaults = false).encodeToByteArray( MyMessage(15)) // [0x08, 0x0f]
val decoded2 = ProtoBuf.decodeFromByteArray<MyMessage>(encoded2) // MyMessage(first=15, second=0, third=42)
```

Reason: The compiler does not consider the single-argument versions of `encodeToByteArray` and `decodeFromByteArray` at the point of use as they are implemented as extension functions for ProtoBuf's superclass:
```
public inline fun <reified T : Any> BinaryFormat.encodeToByteArray(value: T): ByteArray =
public inline fun <reified T : Any> BinaryFormat.decodeFromByteArray(bytes: ByteArray): T =
```

This is a leaky abstraction requiring consideration of implementation details, thus making ProtoBuf harder to use.

Current workarounds:
* Use a star import (drawback: namespace pollution):
    ```
    import kotlinx.serialization.*
    ```
* Use extra imports for extension functions (drawback: dependency on implementation details):
    ```
    import kotlinx.serialization.encodeToByteArray
    import kotlinx.serialization.decodeFromByteArray
    ```

**Describe the solution you'd like**

In decreasing order of preference:
1. Use member functions only, avoiding extension functions as part of the classes' public interface, or
2. document the import requirements in ProtoBuf's usage comments, making the import statements part of the interface.

**Comment by sandwwraith** [comment]
That's not what can bother you everyday, because when you type new code, you'll see both members and extensions in IDE's auto-completion pop-up window -- and IDE will add all necessary imports for you. Since they're public functions, they're not implementation details, they're just convenient overloads. Moreover, star imports are used in many style guides (e.g. ktor's one: https://ktor.io/quickstart/code-style.html#with-star-imports), so that is not a problem too.

The problem happens only when you migrate old code from pre-1.0 versions: IDEA complains about an incorrect number of function arguments, instead of suggesting importing extensions. That's a UX problem that can be solved in a Kotlin plugin in the IDE.

**Comment by OliverO2** [comment]
OK, it seems you need the reified type so using member functions of `BinaryFormat` is not an option. In this case, making the IDE provide a little more assistance would certainly be helpful.
