### ISSUE TITLE
Sealed class serializer needs access to KClass.serializer(), marked @InternalSerializationApi

### ISSUE THREAD

**Issue by edenman** [Kotlin/kotlinx.serialization#991]
**What is your use-case and why do you need this feature?**
I just updated to 1.0.0-RC and now I'm getting this error:
```This declaration is experimental and its usage must be marked with '@kotlinx.serialization.InternalSerializationApi' or '@OptIn(kotlinx.serialization.InternalSerializationApi::class)'```
I can add `languageSettings.useExperimentalAnnotation("kotlinx.serialization.InternalSerializationApi")` for now, but I'd like some more clarity on why this method has been marked internal.  I'm doing something that doesn't seem that crazy to me and seems like it should be supported.

Here's the repro project branch:
https://github.com/edenman/kmpPlayground/compare/edenman/kupdates
And the problematic call:
https://github.com/edenman/kmpPlayground/blob/edenman/kupdates/shared/src/commonMain/kotlin/chat/quill/data/OneOfSerializer.kt#L30

**Describe the solution you'd like**
A non-internal way to get serializers from a list of `KClass` instances

**Comment by edenman** [comment]
I can switch my code to use `serializer(KType): KSerializer<Any>?` but that doesn't offer any type safety :( There's a good bit of "don't use this" in the comment on `KClass.serializer()` but I don't see anything about _why_ it's a bad idea.  I know that the KClass in question is a "plain @Serializable class".
```
/**
 * Retrieves a [KSerializer] for the given [KClass] or returns `null` if none is found.
 * The given class must be annotated with [Serializable] or be one of the built-in types.
 * It is not recommended to use this method for anything, but last-ditch resort, e.g.
 * when all type info is lost, your application has crashed and it is the final attempt to log or send some serializable data.
 *
 * This API is not guaranteed to work consistent across different platforms or
 * to work in cases that slightly differ from "plain @Serializable class".
 */
```

**Comment by rjaros** [comment]
I use this method as well in KVision:
https://github.com/rjaros/kvision/blob/master/kvision-modules/kvision-common-remote/src/jsMain/kotlin/pl/treksoft/kvision/remote/RemoteAgent.kt

**Comment by pdvrieze** [comment]
The function in question requires reflection to work. The "safe" way to make this work is to do it as a contextual serializer. You can register the serializer in a serial module and then retrieve it from the module (it is public api as well).

A big problem with reflection based serialization is that it opens all kinds of security issues when unexpected types are deserialized.

**Comment by qwwdfsad** [comment]
Thanks for the report!

>I can switch my code to use serializer(KType): KSerializer<Any>? but that doesn't offer any type safety :(

This is where we can probably improve either API or documentation. Casting the resulting `KSerializer<Any>` to the `KSerializer<T>` where `T` is the original type, associated with `KType`, is completely safe. We just don't have a way to express it in the type system (maybe we should have introduced `<T> serializer(KType): KSerializer<T>` instead tho).
Using this method is a preferable way to go.

>I'd like some more clarity on why this method has been marked internal.

We'll improve that. Documentation has a short note on it:
>This API is not guaranteed to work consistently across different platforms or
 to work in cases that slightly differ from "plain @Serializable class".

though it's clearly not enough. In general, there is not enough type information to retrieve serializer from an arbitrary `KClass`, especially on platforms different from JVM. This is a fundamental restriction, not a "not yet implemented".

Some examples of unsupported types (`KClass.serializer()` will return `null`) on JS/Native:
* Any `@Serializable` classes with named companion object
* Any class with generic parameter, e.g. `List<Int>`
* Enums that are not marked with `@Serializable` explicitly
* Any interface

On JVM:
* Any class that is marked with `@Serializable(with = SomeSerializer::class)`

So, in general, `KClass.serializer` should be used as a tool as the last resort. E.g. when your whole application has crashed, all you have is some erased `Any` value and you want to log it in a serializable value (or answer with it to HTTP call that crashed your app). Any other usages are strongly discouraged and it is recommended to capture `KType` instead of `KClass` instead

**Comment by edenman** [comment]
This is great information, thanks @qwwdfsad.  I think a `<T> serializer(KType): KSerializer<T>` would make this much more ergonomic.  Even then, it's still annoying that I have to figure out how to turn my KClass into a Type, is there a cross-platform way to do that?  I only see the JVM-only `createType()`

For now I'm just going to add `languageSettings.useExperimentalAnnotation("kotlinx.serialization.InternalSerializationApi")`.  I know that none of the classes in question have any of these red flags (and my project is JVM-only for now anyway).

**Comment by rjaros** [comment]
I'm on Kotlin 1.4.0 JS (legacy) and serialization 1.0.0-RC.

When I replace my `T::class.serializer()` call with `fun <reified T> serializer(): KSerializer<T>` call in a complex use case (nested suspending inline function calls from external library, unfortunately I can't reproduce it in a simple application), I hit an error:
```
Error: This marker function should never been called. Looks like compiler did not eliminate it properly. Please, report an issue if you caught this exception.
```
The following code is generated:
```
serializer(getReifiedTypeParameterKType(typeClosure$RET))

...

Kotlin.getReifiedTypeParameterKType = function (typeParameter) {
    throwMarkerError();
  };
  function throwMarkerError() {
    throw new Error('This marker function should never been called. ' + 'Looks like compiler did not eliminate it properly. ' + 'Please, report an issue if you caught this exception.');
  }

```
This `T::class.serializer()` works without problems returning correct serializer.

**Comment by qwwdfsad** [comment]
@rjaros this is clearly a bug. Please file a separate issue.

@edenman 
> I have to figure out how to turn my KClass into a Type

Such conversion has similar caveats to `kClass.serializer()`. E.g. all its type arguments are already erased and cannot be restored. I would recommend either using `typeOf` directly, or introducing an inline reified function to your API that calls `typeOf<T>` under the hood

**Comment by rjaros** [comment]
@qwwdfsad I've already done that: 
https://youtrack.jetbrains.com/issue/KT-41282

**Comment by edenman** [comment]
> Such conversion has similar caveats to `kClass.serializer()`. E.g. all its type arguments are already erased and cannot be restored. I would recommend either using `typeOf` directly, or introducing an inline reified function to your API that calls `typeOf<T>` under the hood

Yeah, that's not really an approach I can use the way I'm currently doing things. Until there's a better way to get the list of subtypes of a sealed class, I'll just keep using the kClass.serializer() method.

**Comment by qwwdfsad** [comment]
@edenman sure! We realize that `typeOf` approach is not always available, that's why we left `kClass.serializer`.
It can be okay sometimes, but we really want to discourage its usages when possible and give a clear understanding of why this method is potentially dangerous and marked as `Internal`
